- src/resharper-unity/NamingConsistencyWarningSuppressor.cs
- src/resharper-unity/resharper-unity.csproj
This PR suppresses naming warnings on MonoBehaviour's event handlers.
(eg. AnimatorIK has a warning suggesting to rename it to AnimatorIk with the default rules, thus breaking code if applied)
> Suppress naming consistency checks for MonoBehaviours events

- src/resharper-unity/.editorconfig
- src/resharper-unity/ProjectModel/Properties/Flavours/UnityProjectFlavor.cs
- src/resharper-unity/Settings/PerProjectSettings.cs
- src/resharper-unity/resharper-unity.csproj
Creates an in-memory per-project settings layer for each unity project. The layer is invisible, and cannot be edited, but can be overridden by the normal `.csproj.dotSettings` and `.csproj.dotSettings.user` files.
The following settings are written to the layer, to act as defaults:
* Disables the `Assets` and `Assets\Scripts` folders as namespace providers. ReSharper will no longer suggest `Assets` or `Scripts` should be part of the namespace (#6)
* Defaults Unity projects to C#5 (#5)
> In-memory per-project settings

- src/resharper-unity/annotations/UnityEditor.xml
- src/resharper-unity/annotations/UnityEngine.xml
- src/resharper-unity/resharper-unity.nuspec
I added the items that I know for certainty are not null.  Probably could be more added in the future but this gets the most common items that can never be null.
> Adding initial annotations for UnityEngine and UnityEditor not null items

- src/resharper-unity/annotations/UnityEngine.xml
All the UnityEngine.Debug.Assert* methods have updated with external
annotations to be AssertionMethods. This allows users to use these
methods instead of the System.Diagnostic.Debug.Assert* methods.
Resharper will identify these methods as halting when their condition is
false.
> Unity.Debug methods annotated as AssertionMethods

- build.ps1
- resharper/src/build-local.ps1
Changes `build-local.ps1` to make it quicker to get from the command line to a running plugin in Rider.
* Only builds the Rider project and not the ReSharper or test projects (tests can be built and run from within Visual Studio)
* Packages the Rider project
* Runs `gradlew runIde`
It also doesn't do nuget restore. If a full build is required, run `build.ps1` in the root dir.
> Improve local build process

- resharper/src/resharper-unity/Unity3dRider/Assets/Plugins/Editor/JetBrains/RiderAssetPostprocessor.cs
Original reference is 
C:/Program Files/Unity 2017.2.0b3/Editor/Data/UnityExtensions/Unity/TestRunner/net35/unity-custom/nunit.framework.dll
Updated one is 
C:/Program Files/Unity 2017.2.0b3/Editor\Data/Managed/nunit.framework.dll
See comparison 
https://youtrack.jetbrains.com/_persistent/image2.png?file=74-435202&c=true&updated=1501665019076
Original one has System.Web.UI type, and thus doesn't play fine with Re# unit test runner.
> Change reference to nunit.framework.dll

- resharper/src/resharper-unity/Psi/ShaderLab/Parsing/ParserMessages.cs
- resharper/src/resharper-unity/Psi/ShaderLab/Parsing/ShaderLab.psi
- resharper/test/data/psi/shaderLab/parsing/BlendOp.shader
- resharper/test/data/psi/shaderLab/parsing/BlendOp.shader.gold
- resharper/test/src/Psi/ShaderLab/Parsing/ParserTests.cs
https://docs.unity3d.com/Manual/SL-Blend.html
`BlendOp N Op`
`BlendOp N OpColor, OpAlpha` 
Allows referencing properties when using `BlendOp`.
Checked in Unity 2017, BlendOp.shader compiles fine and was erroneously highlighted in Rider.
Fixes https://youtrack.jetbrains.com/issue/RIDER-8386
> Fixes RIDER-8386 (unable to reference property in BlendOp)

- resharper/src/resharper-unity/Unity3dRider/Assets/Plugins/Editor/JetBrains/RiderAssetPostprocessor.cs
- resharper/src/resharper-unity/Unity3dRider/Assets/Plugins/Editor/JetBrains/RiderPlugin.cs
Consider VS2017 MSBuild + dotnet framework targetpack 4.7 will not load project with TargetFrameworkVersion = 4.5, so we need to allow customization.
Unfortunately proper detection of installed targets packs is complicated.
> Allow to set desired TargetFrameworkVersion in Unity

- resharper/src/resharper-unity/Unity3dRider/Assets/Plugins/Editor/JetBrains/RiderPlugin.cs
On MAC there is a bug in Unity - Recently used external app disappears from the list of possibilities, when you select other Editor.
So on Rider settings Tab we provide am alternative UI to help find and set Rider as default editor.
> Allow to see found Rider executables and make one  of them a Default External Editor

- resharper/src/resharper-unity/annotations/UnityEngine.AnimationModule.xml
- resharper/src/resharper-unity/annotations/UnityEngine.CoreModule.xml
- resharper/src/resharper-unity/annotations/UnityEngine.IMGUIModule.xml
- resharper/src/resharper-unity/resharper-unity.rider.nuspec
- resharper/src/resharper-unity/resharper-unity.wave08.nuspec
- rider/src/main/resources/META-INF/plugin.xml
Unity 2017.2 splits UnityEngine.dll into separate modules, so the existing UnityEngine.dll annotations no longer work. This PR adds new annotation files for the new assemblies, based on the existing annotations.
Fixes #207
> Add annotations for modularised UnityEngine assemblies

- resharper/src/resharper-unity/Psi/ShaderLab/Parsing/ParserMessages.cs
- resharper/src/resharper-unity/Psi/ShaderLab/Parsing/ShaderLab.psi
- resharper/src/resharper-unity/Psi/ShaderLab/Parsing/ShaderLabTokenType.NodeSets.cs
- resharper/src/resharper-unity/Psi/ShaderLab/Parsing/ShaderLabTokenType.Tokens.generated.cs
- resharper/src/resharper-unity/Psi/ShaderLab/Parsing/ShaderLabTokenType.Tokens.xml
- resharper/test/data/psi/shaderLab/parsing/PropertiesTextureValue.shader
- resharper/test/data/psi/shaderLab/parsing/PropertiesTextureValue.shader.gold
- resharper/test/src/Psi/ShaderLab/Parsing/ParserTests.cs
Allows for parsing of several texture property values in addition to `LigthMapMode`:
* TexGen (legacy Unity 5.0, does nothing now and shows warning in Editor)
* Matrix (legacy, does nothing now and shows warning in Editor)
* Texture dimension
Fixes https://youtrack.jetbrains.com/issue/RIDER-8917
> RIDER-8917  parse texture property values

- resharper/src/resharper-unity/Psi/ShaderLab/Parsing/ParserMessages.cs
- resharper/src/resharper-unity/Psi/ShaderLab/Parsing/ShaderLab.psi
- resharper/test/data/psi/shaderLab/parsing/TagDeclaration.shader
- resharper/test/data/psi/shaderLab/parsing/TagDeclaration.shader.gold
- resharper/test/src/Psi/ShaderLab/Parsing/ParserTests.cs
Right now we only allow tag declarations to have string literals as name and value. Actually, 
`Identifier = Identifier` is valid syntax too.
Fixes RIDER-9214 (at least the one on the user screenshot).
https://youtrack.jetbrains.com/issue/RIDER-9214
> Allow ID = ID in tag declaration (RIDER-9214)

- resharper/src/resharper-unity/Feature/Services/Descriptions/UnityEventFunctionDescriptionProvider.cs
This is required for an upcoming Rider/R# feature that shows descriptions in Generate window. Methods presented there come from no SourceFile, and therefore do not belong to unity project.
The way of checking used in this PR uses containing class instead, which is declared in a proper file and can be properly checked for IsFromUnityProject.
> Provide event descriptions for synthetic event methods

- resharper/src/resharper-unity/Unity3dRider/Assets/Plugins/Editor/JetBrains/RiderAssetPostprocessor.cs
gmcs.rsp and smcs.rsp will still be used if mcs.rsp is not present, but not if it is.
> Added support for mcs.rsp file for Unity 5.5 or newer.

- resharper/Directory.Build.targets
- resharper/src/resharper-unity/resharper-unity.rider.csproj
- resharper/src/resharper-unity/resharper-unity.wave09.csproj
- resharper/test/src/tests.rider.csproj
- resharper/test/src/tests.wave09.csproj
Couple of fixes to the msbuild files:
* Work around unnecessary rebuilds due to SDK bug (see [RSRP-465228](https://youtrack.jetbrains.com/issue/RSRP-465228))
* Fix a warning about an incorrect version on dotnet restore
* Add `JET_MODE_REPORT_EXCEPTIONS` for debug builds - will give more useful data in exceptions during debug and test
> Misc msbuild fixes

- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorConfiguration.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToPlayerConfiguration.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/attach/UnityProcessPickerDialog.kt
Should fix #262.
```
19:45:01.123 |E| DebuggerWorker                | Unable to start debug session Could not resolve host 'localhost'
--- EXCEPTION #1/2 [SocketException]
Message = “Could not resolve host 'localhost'”
ExceptionPath = Root.InnerException
NativeErrorCode = 11001
ClassName = System.Net.Sockets.SocketException
HResult = E_FAIL=EFail=80004005
Source = System
StackTraceString = “
at System.Net.Dns.Error_11001 (System.String hostName) [0x00015] in <22f1a38c4c7d45529e36fef933c973df>:0 
at System.Net.Dns.hostent_to_IPHostEntry (System.String originalHostName, System.String h_name, System.String[] h_aliases, System.String[] h_addrlist) [0x00068] in <22f1a38c4c7d45529e36fef933c973df>:0 
at System.Net.Dns.GetHostByName (System.String hostName) [0x00027] in …
```
> replaced localhost usage on FE with 127.0.0.1

- resharper/src/resharper-unity/annotations/UnityEditor.xml
- resharper/src/resharper-unity/annotations/UnityEngine.CoreModule.xml
- resharper/src/resharper-unity/annotations/UnityEngine.xml
Some Unity attributes don't set `AttributeTargets`, put they can only realistically be applied to certain targets. This adds the targets in as external annotations - ReSharper treats this as though they were "real" and shows a warning if the attributes are applied to the wrong target type.
> Add attribute target usage annotations

- resharper/src/resharper-unity.sln.DotSettings
- resharper/src/resharper-unity/Daemon/UsageChecking/UsageInspectionsSuppressor.cs
- resharper/src/resharper-unity/ProjectExtensions.cs
Handles [an exception](https://youtrack.jetbrains.com/v2/issue/RIDER-11332) that happens sometimes when failing to retrieve CurrentTargetFrameworkId for a project.
I was unable to reproduce the exception, but it is a popular one on a tracker. I think that the proper way to fix this would be to replace all of the `ProjectExtensions` that check for Unity assembly references with something more clever that will not be prone to such errors. Anyway, this fix should at least prevent users from seeing Unity plugin exception on non-Unity projects.
> Fix exception that sometimes happens in UsageInspectionsSuppressor

- resharper/src/resharper-unity.sln.DotSettings
- resharper/src/resharper-unity/Feature/Services/CodeCompletion/UnityEventFunctionBehavior.cs
- resharper/src/resharper-unity/Feature/Services/CodeCompletion/UnityEventFunctionRule.cs
- resharper/src/resharper-unity/resharper-unity.resharper.nuspec
- resharper/src/resharper-unity/resharper-unity.rider.nuspec
- resharper/test/data/codeCompletion/Action/MonoBehaviour07.cs
- resharper/test/data/codeCompletion/Action/MonoBehaviour07.cs.gold
- resharper/test/data/codeCompletion/Action/MonoBehaviour08.cs
- resharper/test/data/codeCompletion/Action/MonoBehaviour08.cs.gold
- resharper/test/data/codeCompletion/Action/MonoBehaviour09.cs
- resharper/test/data/codeCompletion/Action/MonoBehaviour09.cs.gold
- resharper/test/data/codeCompletion/List/MonoBehaviour07.cs
- resharper/test/data/codeCompletion/List/MonoBehaviour07.cs.gold
- resharper/test/data/codeCompletion/List/MonoBehaviour08.cs
- resharper/test/data/codeCompletion/List/MonoBehaviour08.cs.gold
- resharper/test/src/Feature/Services/CodeCompletion/UnityEventFunctionCompletionActionTest.cs
- resharper/test/src/Feature/Services/CodeCompletion/UnityEventFunctionCompletionListTest.cs
Fixes code completion of event functions in situations like:
```cs
{
OnAnim{caret}
[SerializeField] public int Value;
}
```
ReSharper would think that the attribute of the following field as actually an indexer in a property declaration, or an array specifier in a field declaration.
This PR adds tests and fixes completion.
Fixes #259
> Fix Unity event function before attributed fields

- resharper/src/resharper-unity/ProjectModel/MetaFileTracker.cs
This change will cause Rider to notify the front end about `.meta` file operations, allowing the front end to keep the Virtual File System up to date. This in turn means that the Solution Explorer (and VCS windows, etc.) will be up to date with newly added/deleted/renamed `.meta` files.
Currently, if "Show All Files" is enabled, Rider can show `.cs.meta` files even after they're deleted, and make it look like `.cs.meta` files haven't been moved when the parent `.cs` file is moved.
This is all handled by Rider infrastructure - whenever a project model transaction is started, Rider will delegate file system operations to the protocol and the VFS.
> Notify front end when modifying meta files

- resharper/src/resharper-unity/Feature/Services/ContextActions/AttributeUtil.cs
- resharper/src/resharper-unity/Feature/Services/ContextActions/AutoPropertyToSerializedBackingFieldAction.cs
- resharper/src/resharper-unity/Feature/Services/ContextActions/MarkFieldNonSerializedAction.cs
- resharper/src/resharper-unity/Feature/Services/ContextActions/MarkSerializeFieldAction.cs
- resharper/src/resharper-unity/Feature/Services/ContextActions/UnityContextActions.cs
- resharper/src/resharper-unity/Feature/Services/QuickFixes/UseSerializedBackingFieldFix.cs
- resharper/src/resharper-unity/resharper-unity.resharper.nuspec
- resharper/src/resharper-unity/resharper-unity.rider.nuspec
- resharper/test/data/intentions/ContextActions/AutoPropertyToSerializedBackingField/Availability01.cs
- resharper/test/data/intentions/ContextActions/AutoPropertyToSerializedBackingField/Availability02.cs
- resharper/test/data/intentions/ContextActions/AutoPropertyToSerializedBackingField/Test01.cs
- resharper/test/data/intentions/ContextActions/AutoPropertyToSerializedBackingField/Test01.cs.gold
- resharper/test/data/intentions/QuickFixes/UseSerializedBackingField/Availability/Test01.cs
- resharper/test/data/intentions/QuickFixes/UseSerializedBackingField/Availability/Test01.cs.gold
- resharper/test/data/intentions/QuickFixes/UseSerializedBackingField/Availability/Test02.cs
- resharper/test/data/intentions/QuickFixes/UseSerializedBackingField/Availability/Test02.cs.gold
- resharper/test/data/intentions/QuickFixes/UseSerializedBackingField/Test01.cs
- resharper/test/data/intentions/QuickFixes/UseSerializedBackingField/Test01.cs.gold
- resharper/test/data/intentions/QuickFixes/UseSerializedBackingField/Test02.cs
- resharper/test/data/intentions/QuickFixes/UseSerializedBackingField/Test02.cs.gold
- resharper/test/src/Intentions/ContextActions/AutoPropertyToSerializedBackingFieldTests.cs
- resharper/test/src/Intentions/QuickFixes/UseSerializedBackingFieldFixTests.cs
- resharper/test/src/tests.resharper.csproj
- rider/src/main/resources/META-INF/plugin.xml
Also moves existing (three) context actions to new "C# (Unity)" group of context actions.
Fixes #195
> Add context action to convert auto-property to property with serialized backing field

- resharper/src/resharper-unity/Feature/Services/QuickDoc/UnityExternalDocumentationContextProvider.cs
- resharper/src/resharper-unity/Help/ShowUnityHelp.cs
- resharper/src/resharper-unity/Psi/Resolve/SyncVarHookReference.cs
- resharper/src/resharper-unity/Psi/Resolve/UnityEventFunctionReference.cs
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/quickDoc/UnityDocumentationProvider.kt
- rider/src/main/resources/META-INF/plugin.xml
An alternative approach, instead of waiting for an API in the protocol and in ReSharper.
Sets up a context consumer, similar to ReSharper's context highlighters that gets called when the context changes, e.g. the cursor is on a new symbol. If that symbol is a Unity symbol, pushes the fully qualified name into the `CustomData` protocol element. When the user calls the _External Documentation_ action, or clicks the icon in the QuickDoc popup, a new `DocumentationProvider` on the front end will check `CustomData` for the symbol name. If present, it generates a URL for the docs, either for locally installed docs, or Unity's search page.
Fixes #98 
Still to do:
> [WIP] Open external documentation for Unity symbols

- resharper/src/resharper-unity/Unity3dRider/Assets/Plugins/Editor/JetBrains/RiderPlugin.cs
I am a bit confused that 
path to documentation is done both on backend in 
ShowUnityHelp.GetDocumentationRoot()
and on frontend in
UnityDocumentationProvider
Thus I would rather not touch it myself.
>  add app_path and app_content_path to EditorInstance.json

- resharper/src/resharper-unity/ShaderLab/Feature/Services/VisualElements/VisualElementFactory.cs
- resharper/src/resharper-unity/ShaderLab/Psi/Colors/ShaderLabColorReference.cs
- resharper/src/resharper-unity/ShaderLab/Psi/Parsing/IShaderLabParser.cs
- resharper/src/resharper-unity/ShaderLab/Psi/Parsing/ShaderLab.psi
- resharper/src/resharper-unity/ShaderLab/Psi/Parsing/ShaderLabParser.cs
- resharper/test/data/ShaderLab/Daemon/Stages/Colors/EdgeCasesAndErrors.shader
- resharper/test/data/ShaderLab/Daemon/Stages/Colors/EdgeCasesAndErrors.shader.gold
- resharper/test/data/ShaderLab/Daemon/Stages/Colors/PropertyColor.shader
- resharper/test/data/ShaderLab/Daemon/Stages/Colors/PropertyColor.shader.gold
- resharper/test/src/ShaderLab/Psi/Colors/ShaderLabColorHighlightingTests.cs
Round to valid colour ARGB values, only parse for colours, not vector
Fixes #384
> Fix colour property handling in shaders

- unity/JetBrains.Rider.Unity.Editor/EditorPlugin/ModificationPostProcessor.cs
- unity/JetBrains.Rider.Unity.Editor/EditorPlugin/OnOpenAssetHandler.cs
You are currently forcing a sync everytime the user clicks on a cs file or a log entry. This seems fine, but doesn't happen in Visual Studio, i've tried to mitigate that with these changes, and you should now, only sync the project when needed. (Provided I've caught all the cases)
This is currently, when a cs file has been created, deleted or renamed.
It might be worthwhile considering other situations in the future (assembdefs, rsp, etc)
> Ensure we only sync the solution when needed.

- resharper/src/resharper-unity/ShaderLab/Daemon/ContextHighlighters/ShaderLabUsageContextHighlighterAvailability.cs
- resharper/src/resharper-unity/ShaderLab/Daemon/ContextHighlighters/ShaderLabUsagesContextHighlighter.cs
- resharper/test/data/ShaderLab/ContextHighlighters/PropertyUsage/PropertyUsage01.shader
Previously, it would highlight if the caret was anywhere in the property declaration
> Fix bug to only highlight ShaderLab property usage if caret is on name

- resharper/src/resharper-unity/ProjectExtensions.cs
- resharper/src/resharper-unity/Settings/PerProjectSettings.cs
- rider/src/main/kotlin/com/jetbrains/rider/UnityReferenceDiscoverer.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorer.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ui/UnityUIManager.kt
Check Assets folder and UnityEngine reference to hide Nuget toolwindow.
> Improve heuristics for detecting Unity-generated project on frontend

- resharper/src/resharper-unity/Rider/UnityPluginDetector.cs
- resharper/src/resharper-unity/Rider/UnityRefreshTracker.cs
fix "Auto Refresh from Rider - should fire after refactoring, but fires in the middle #535"
> Rewrite Refresh rules to use transactions instead of PM changes

- resharper/src/resharper-unity/ProjectExtensions.cs
- resharper/src/resharper-unity/Rider/UnityPluginInstaller.cs
- resharper/src/resharper-unity/Rider/UnityVersionDetector.cs
The worst problem might be, if we install full plugin in the old Unity. But it should not happen.
https://github.com/JetBrains/resharper-unity/issues/510
> Use Project version to directly install Basic/Full EditorPlugin

- resharper/src/.idea/.idea.resharper-unity/.idea/runConfigurations/runIde.xml
- resharper/src/GradleLauncher/GradleLauncher.csproj
- resharper/src/GradleLauncher/Program.cs
- resharper/src/GradleLauncher/Properties/AssemblyInfo.cs
- resharper/src/resharper-unity.sln
**WORK IN PROGRESS. DO NOT MERGE**
This PR is cleaning up and speeding up the build. Specifically:
Stretch goals :)
- :x: Create shared run configuration to allow _debugging_ Rider with plugin directly from Rider - This requires a custom run configuration
- :x: Create shared run configuration to allow running/debugging ReSharper from Rider - didn't investigate
- :x: Add schema to the errors.xml files - didn't investigate
- :x: Ensure PsiGen works correctly with just the Rider project. See [RIDER-14366](https://youtrack.jetbrains.com/issue/RIDER-14366) - No changes to existing implementation
Notable differences:
* EditorPlugin will be built in Release mode. Was defaulting to Debug
* Gradle script won't do a rebuild if only the version number changes. I don't think this will cause a problem …
> [WIP] Clean up and speed up build

- unity/EditorPlugin/AssetPostprocessors/CsprojAssetPostprocessor.cs
Use a new Unity 2017.4+ API to modify the .csproj files in memory. Unity will only save to the file if the contents have changed.
> Use in-memory csproj modification API in 2017.4+

- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/UnityDebuggerOutputListener.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/attach/UnityAttachConfiguration.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/attach/UnityAttachEditorDebugger.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/attach/UnityAttachEditorDebuggerProvider.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/attach/UnityAttachProfileState.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/attach/UnityAttachRunProfile.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/attach/UnityPlayer.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/attach/UnityProcessListener.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/attach/UnityProcessPickerDialog.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/attach/UnityRunUtil.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorProfileState.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorRunConfiguration.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/UnityUtils.kt
- rider/src/main/resources/META-INF/plugin.xml
* Fixes typo in regex to discover debugger port in iPhone players, e.g.
"iPhonePlayer(Matts-iPhone-7):56000"
* Shows players with debugging disabled in the dialog (but not selectable)
* Uses the IP address from the multicast message to work around issues with multiple interfaces. E.g. the iPhone reports the internal IP address of the mobile data network, which isn't reachable from the current network
* Provides better guidance when a player debug session fails to connect
> Improve support for debugging remote players

- resharper/src/resharper-unity/CSharp/Feature/Services/LiveTemplates/Rider/UnityFileTemplatesOptionsPage.cs
- rider/src/main/kotlin/com/jetbrains/rider/settings/templates/UnityFileTemplatesOptionPage.kt
- rider/src/main/resources/META-INF/plugin.xml
Adds a "Unity" page to Rider's File Templates section, allowing editing/adding/deleting Unity specific file templates.
> Enable editing Unity specific file templates

- unity/EditorPlugin/AssetPostprocessors/CsprojAssetPostprocessor.cs
- unity/EditorPlugin/AssetPostprocessors/SlnAssetPostprocessor.cs
Unity's old scripting runtime version of Mono does not support XLinq's `XObject.Changed` event (it does nothing), so we weren't saving any modifications to .csproj files. This PR makes the change tracking manual.
See #662
> Fix C# projects not being modified with old runtime

- resharper/src/resharper-unity/Rider/UnitTesting/RunViaUnityEditorStrategy.cs
Looks like this.
Actually, there's no difference between run and debug for us at all, but Debug doesn't attach automatically and that confuses people, so I've disabled it too.
Disabling the buttons themselves is not possible right now due to internal workings of unit tests and us using NUnitTestProvider and having 2 different strategies for it. Maybe in `183`?
> RIDER-17815 do not run debug and dotCover for Unity run strategy

- resharper/src/resharper-unity/Json/Daemon/Stages/Resolve/UnresolvedReferenceErrorHandler.cs
- resharper/test/data/Json/Intentions/QuickFixes/DuplicateItems/Availability/Test02.asmdef.gold
- resharper/test/data/Json/Intentions/QuickFixes/ReferencingSelf/Availability/Test01.asmdef.gold
Temporarily disable the error for invalid asmdef references, because it can't resolve against assembly definitions defined in files external to the project. A more permanent fix is to include those files into a custom PSI module. I'll raise another issue to do that post 2018.2
Fixes #647. Fixes RIDER-17700
> Disable error for invalid asmdef reference

- unity/EditorPlugin/AssetPostprocessors/CsprojAssetPostprocessor.cs
SetManuallyDefinedCompilerSettings - must be called for unity version < 2017
In existing code if unity version is less then 2017 - this code will be skipped
Please accept asap
Tarkov developer will be very happy )
> Version check typo fix

- unity/EditorPlugin/NonUnity/RiderProtocolController.cs
Avoid using JsonConvert.SerializeObject which is slow, use StringBuilder instead.
> Optimize plugin startup performance

- resharper/src/resharper-unity/annotations/UnityEditor.xml
- resharper/src/resharper-unity/annotations/UnityEngine.AnimationModule.xml
- resharper/src/resharper-unity/annotations/UnityEngine.CoreModule.xml
- resharper/src/resharper-unity/annotations/UnityEngine.IMGUIModule.xml
- resharper/src/resharper-unity/annotations/UnityEngine.xml
- resharper/test/data/CSharp/Intentions/QuickFixes/RedundantAttributeOnTarget/Availability/RedundantFieldAttribute.cs
- resharper/test/data/CSharp/Intentions/QuickFixes/RedundantAttributeOnTarget/Availability/RedundantFieldAttribute.cs.gold
- resharper/test/data/CSharp/Intentions/QuickFixes/RedundantHideInInspectorAttribute/Availability/Test02.cs
- resharper/test/data/CSharp/Intentions/QuickFixes/RedundantHideInInspectorAttribute/Availability/Test02.cs.gold
Remove some incorrect implicit use annotations, and remove others that interfere with existing usage suppression (e.g. `PropertyAttribute`, which is a base type of `HeaderAttribute` which would mark a serialised field as in use, but the code does that better).
Fixes [RIDER-19408](https://youtrack.jetbrains.com/issues/RIDER-19408)
> Remove incorrect implicit use annotations

- resharper/src/resharper-unity/CSharp/Daemon/Stages/Analysis/UnityObjectEqualityProblemAnalyzer.cs
- resharper/test/data/CSharp/Daemon/Stages/Analysis/UnityObjectEqualitySuspiciousComparisonWarning.cs
- resharper/test/data/CSharp/Daemon/Stages/Analysis/UnityObjectEqualitySuspiciousComparisonWarning.cs.gold
- resharper/test/src/CSharp/Daemon/Stages/Analysis/UnityObjectEqualitySuspiciousComparisonWarningTests.cs
Shows suspicious comparison warning when comparing two objects that derive from `UnityEngine.Object` but don't have a common subtype, such as `Collider` and `Rigidbody`.
Fixes [RIDER-18671](https://youtrack.jetbrains.com/issues/RIDER-18671)
> Show suspicious comparison warning for Unity objects

- resharper/src/resharper-unity/CSharp/Daemon/Stages/Analysis/RedundantEventFunctionProblemAnalyzer.cs
- resharper/test/data/CSharp/Daemon/Stages/Analysis/RedundantEventFunctionWarning.cs
- resharper/test/data/CSharp/Daemon/Stages/Analysis/RedundantEventFunctionWarning.cs.gold
- resharper/test/src/CSharp/Daemon/Stages/Analysis/RedundantEventFunctionWarningTests.cs
Don't highlight if it's hiding a base implementation, or it's overriding a virtual method
Fixes [RIDER-19894](https://youtrack.jetbrains.com/issue/RIDER-19894)
> Improve redundant event function warnings

- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/PackagesManager.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorRunConfiguration.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/EditorInstanceJson.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/FileUtils.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/UnityInstallationFinder.kt
Should hopefully stop the VFS from working with stale files and thinking files are still valid when they've been deleted.
> Refresh VFS before handling external files

- unity/EditorPlugin/PluginEntryPoint.cs
- unity/EditorPlugin/UnityEventLogSender.cs
UnityException: get_isPlaying is not allowed to be called during serialization, call it from OnEnable instead. Called from ScriptableObject 'FunctionalityIsland'.
See "Script Serialization" page in the Unity Manual for further details.
JetBrains.Rider.Unity.Editor.UnityEventCollector+<>c__DisplayClass3_0.<ApplicationOnLogMessageReceived>b__0 ()
JetBrains.Rider.Unity.Editor.MainThreadDispatcher.Queue (System.Action action)
> backport fix to keep PlayModeSavedState

- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/attach/UnityProcessPickerDialog.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelView.kt
In the Attach to Unity Process dialog, double clicking an item in the list will now close the dialog and attach to that process.
> Double click to attach to a Unity process

- resharper/resharper-unity/src/ProjectModel/Caches/UnityProjectFileCacheProvider.cs
- resharper/resharper-unity/src/Settings/PerProjectSettings.cs
It was incorrectly treating this as though it were "default", and trying to apply heuristics.  It now correctly treats this as "latest", e.g. C# 7.3 at time of going to press.
> Fix C# language level override with "latest"

- unity/EditorPlugin/AssetPostprocessors/CsprojAssetPostprocessor.cs
- unity/EditorPlugin/PluginEntryPoint.cs
Otherwise when Unity version is updated Unity doesn't update csproj and we end up with https://youtrack.jetbrains.com/issue/RIDER-21035
> Call SyncSolution on each Unity startup

- resharper/.idea/.idea.resharper-unity/.idea/runConfigurations/runIde__offline_.xml
- resharper/gradle-launcher/Program.cs
- rider/model.gradle
* Reverts the default `--offline` behaviour in the Gradle launcher app
* Adds a new "runIde (offline)" shared run configuration. Use this to run Gradle in offline mode so that it doesn't check online for dependencies. I don't know if it's actually faster, but it's very useful when you don't have internet connection. Running in offline mode can prevent running the debug instance of Rider if Gradle needs to download the JRE, which is a runtime dependency. Use the existing "runIde" run configuration to run in online mode in this case.
* Save the rdgen build hash in a reliably consistent location under the project folder
> Minor build updates

- resharper/resharper-unity/src/Rider/UnityInstallationSynchronizer.cs
- resharper/resharper-unity/src/UnityInstallationFinder.cs
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/notifications/OpenUnityProjectAsFolderNotification.kt
**Currently**
When you get pong-tdd from vcs it is opened as a folder.
And ApplicationPath is not populated
So Start Unity action is not availbale and Notification is saying just close project and open it via Unity.
**With this fix**
When project is opened as folder and IsUnityProjectFolder is thue, then ApplicationPath is found and passed to frontend, Start Unity is working and Notification says click here and Unity will be opened and will open Rider with solution.
> Fix isUnity Notification

- resharper/resharper-unity/src/Rider/UnitTesting/RunViaUnityEditorStrategy.cs
- resharper/resharper-unity/src/Rider/UnitTesting/UnityNUnitServiceProvider.cs
- resharper/resharper-unity/src/Rider/UnityEditorProtocol.cs
- rider/protocol/src/main/kotlin/model/rider/RdUnityModel.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/UnityToolWindowManager.kt
Show Notification and focus UnityLogView when compilation before tests was not successful.
> Notify user, when compilation before tests failed

- .gitignore
- resharper/.idea/.idea.resharper-unity/.idea/encodings.xml
- resharper/.idea/.idea.resharper-unity/.idea/misc.xml
- resharper/resharper-unity/src/CSharp/Daemon/Stages/GutterMarks/UnityEventHandlerDetector.cs
- resharper/resharper-unity/src/CSharp/Daemon/Stages/GutterMarks/UnityFieldDetector.cs
- resharper/resharper-unity/src/CSharp/Daemon/Stages/GutterMarks/UnityInitialiseOnLoadCctorDetector.cs
- resharper/resharper-unity/src/CSharp/Daemon/Stages/GutterMarks/UnityTypeDetector.cs
- resharper/resharper-unity/src/CSharp/Feature/Services/QuickFixes/GenerateUnityEventFunctionsFix.cs
- resharper/resharper-unity/src/CSharp/Feature/Services/Refactorings/Rename/UnityEventTargetAtomicRenameFactory.cs
- resharper/resharper-unity/src/Json/Psi/Caches/AsmDefNameCache.cs
- resharper/resharper-unity/src/Yaml/Psi/Caches/MetaFileGuidCache.cs
- resharper/resharper-unity/src/Yaml/Psi/Caches/UnityEventHandlerCacheItem.cs
- resharper/resharper-unity/src/Yaml/Psi/Caches/UnityEventHandlerReferenceCache.cs
- resharper/resharper-unity/src/Yaml/Psi/Resolve/UnityEventTargetReference.cs
- resharper/resharper-unity/src/Yaml/Psi/Search/UnityYamlUsageSearchFactory.cs
- resharper/resharper-unity/src/Yaml/Psi/UnityObjectPsiUtil.cs
- rider/.idea/encodings.xml
- rider/.idea/gradle.xml
* Fix exception on startup - [RIDER-21929](https://youtrack.jetbrains.com/issue/RIDER-21929) (mistyped the ticket in the commit)
* Mark event handlers as in use if they're declared on a base type - #922 
* Fix highlighting for property used as event handler - gets gutter icon/code insight marker
* Fix find usages for properties used as event handlers
Plus sneaky, unrelated fix to stop the Generate event function dialog selecting all items by default when called from the gutter icon or code code insight marker. See [RIDER-22211](https://youtrack.jetbrains.com/issue/RIDER-22211)
> Updates to cache handling and property event handlers

- resharper/resharper-unity/src/CSharp/Rider/Host/Features/Settings/ChangeNamingRuleWindowProvider.cs
- resharper/resharper-unity/src/Rider/OptionsPageBase.cs
- resharper/resharper-unity/src/Rider/UnityOptionsPage.cs
- resharper/resharper-unity/src/Settings/UnitySettings.cs
Allow to set prefix, suffix and disable inspections, until [RIDER-8339](https://youtrack.jetbrains.com/issue/RIDER-8339) is implemented. Will also show the Unity options page when selecting "Inspection: 'Inconsistent Naming'> Change naming rule for 'Unity serialized field'" in the alt+enter menu.
Fixes #928, [RIDER-22026](https://youtrack.jetbrains.com/issue/RIDER-22026), [RIDER-21193](https://youtrack.jetbrains.com/issue/RIDER-21193)
> Increase options for naming Unity serialised fields

- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/PackagesManager.kt
Correctly handles `file:` based packages as local or fully qualified paths (Windows, with drive letters).
Fixes [RIDER-21734](https://youtrack.jetbrains.com/issue/RIDER-21734).
> Resolve local packages with fully qualified paths

- resharper/resharper-unity/src/ProjectExtensions.cs
- resharper/resharper-unity/src/Yaml/Psi/Modules/UnityExternalFilesModuleProcessor.cs
- resharper/resharper-unity/src/Yaml/UnityYamlFileExtensions.cs
Looking at `project.Location` is a mistake, because that's the location of the `.csproj` file, which is the solution directory, so we'll look at way too many files and can parse files we shouldn't be looking at.
This PR changes YAML processing to look in the project model of each Unity project for a `.asmdef` file, and process that directory. Any assembly definitions inside `Assets` or `Packages` will already have been handled and will be skipped. So this will catch any source based packages that live outside of the normal solution structure.
Fixes RIDER-22673
> Fix finding of YAML files for file based packages

- resharper/resharper-unity.sln.DotSettings
- unity/EditorPlugin/PluginEntryPoint.cs
- unity/EditorPlugin/RiderMenu.cs
- unity/EditorPlugin/UnityUtils.cs
Previously RIDER-19688 was fixed by disabling Rider Editor plugin in batch mode, but this fix avoids the same problem by caching unityVersion and thus not trying to get it during AppDomain termination
> Fix for "get_unityVersion is not allowed to be called while application is terminating"

- resharper/resharper-unity/src/Rider/UnityEditorFindUsageResultCreator.cs
- resharper/resharper-unity/src/Yaml/Psi/Modules/UnityExternalFileProperties.cs
- resharper/resharper-unity/src/Yaml/Psi/UnityObjectPsiUtil.cs
- resharper/resharper-unity/src/Yaml/Psi/UnityPathSceneConsumer.cs
- resharper/resharper-unity/src/Yaml/Psi/UnitySceneProcessor.cs
- resharper/resharper-unity/src/Yaml/Psi/UnityYamlConstants.cs
- resharper/resharper-unity/src/Yaml/Rider/Host/Feature/UnityYamlExtraGroupingRulesProvider.cs
- unity/EditorPlugin/Navigation/EntryPoint.cs
- unity/EditorPlugin/Navigation/ShowUtil.cs
- unity/EditorPlugin/Navigation/Window/AbstractUsageElement.cs
- unity/EditorPlugin/Navigation/Window/FindUsagePathElement.cs
- unity/EditorPlugin/Navigation/Window/FindUsagesTreeView.cs
- unity/EditorPlugin/Navigation/Window/FindUsagesTreeViewItem.cs
- unity/EditorPlugin/Navigation/Window/FindUsagesWindow.cs
- unity/EditorPlugin/Navigation/Window/FindUsagesWindowTreeState.cs
- unity/EditorPlugin/Navigation/Window/PrefabElement.cs
- unity/EditorPlugin/Navigation/Window/SceneElement.cs
1. Extract Unity scene hierarchy iterator into class
2. Find usages correctly returs result for Unity 2017 LTS
3. Do not merge different game objects with same names in Find Usages Window in Unity Editor
4. Refactoring
> Fixes in processing Unity scene hierarchy

- unity/EditorPlugin/PluginEntryPoint.cs
Add a little bit of logging around switching between play/pause mode, as well as during refresh.
> Add extra logging for play mode and refresh

- resharper/resharper-unity/src/CSharp/Daemon/UsageChecking/UsageInspectionsSuppressor.cs
- resharper/resharper-unity/src/Internal/DumpPsiForFileAction.cs
- resharper/resharper-unity/src/Settings/UnitySettings.cs
- resharper/resharper-unity/src/UnityApi.cs
- resharper/resharper-unity/src/Yaml/AssetSerializationMode.cs
- resharper/resharper-unity/src/Yaml/ProjectModel/UnityYamlProjectModelElementPresenter.cs
- resharper/resharper-unity/src/Yaml/Psi/Caches/BinaryUnityFileCache.cs
- resharper/resharper-unity/src/Yaml/Psi/Caches/UnityCacheUpdater.cs
- resharper/resharper-unity/src/Yaml/Psi/Modules/UnityExternalFileProperties.cs
- resharper/resharper-unity/src/Yaml/Psi/Modules/UnityExternalFilesModuleFactory.cs
- resharper/resharper-unity/src/Yaml/Psi/Modules/UnityExternalFilesModuleProcessor.cs
- resharper/resharper-unity/src/Yaml/Psi/Modules/UnityExternalFilesPsiModule.cs
- resharper/resharper-unity/src/Yaml/Psi/Modules/UnityMiscFilesProjectPsiModuleProvider.cs
- resharper/resharper-unity/src/Yaml/Psi/Modules/UnityYamlDisableStrategy.cs
- resharper/resharper-unity/src/Yaml/Psi/Modules/UnityYamlPsiSourceFileFactory.cs
- resharper/resharper-unity/src/Yaml/Psi/Search/UnityYamlSearchGuru.cs
- resharper/resharper-unity/src/Yaml/Psi/Search/UnityYamlUsageSearchFactory.cs
- resharper/resharper-unity/src/Yaml/Psi/UnityFileSystemPathExtension.cs
- resharper/resharper-unity/src/Yaml/Psi/UnityYamlPsiSourceFileExtensions.cs
- resharper/resharper-unity/src/Yaml/Rider/Psi/Modules/RiderUnityYamlDisableStrategy.cs
- resharper/resharper-unity/src/Yaml/Rider/UnityYamlFileSizeLogContributor.cs
- resharper/resharper-unity/src/Yaml/Rider/UnityYamlStatistics.cs
- resharper/resharper-unity/src/Yaml/UnityYamlFileExtensions.cs
- resharper/resharper-unity/src/Yaml/UnityYamlSupport.cs
- resharper/resharper-unity/test/src/CSharp/Daemon/UsageChecking/UsageInspectionsSuppressorTest.cs
- resharper/resharper-yaml/src/Psi/Search/YamlReferenceSearcher.cs
Several problems during rename:
* Search domain too wide as part of initial search for usages
* False positives in the trigram index for binary files
* Suspicious references search post rename (it will do the rename, then do a reference search on all files that contain the original text and the renamed text. This can be a huge number of YAML files if the symbol is e.g. `x` or `GameObject`)
This PR:
Things to check in review:
* Validate assumptions made in `ISearchGuru` that the files must contain ALL of the given words
* Threshold of "large binary file" in PSI module processor (currently 10Mb)
* Validate method of invalidating cache when binary file is modified. Do we want to sniff on each modification?
Note that this PR does NOT fix suspicious reference searching. This appears to be …
> Updates for rename performance

- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/PackagesRoot.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorer.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorerNode.kt
This PR makes two changes:
* Project names are only shown for folders at the project root and above (up to `Assets` or `Packages`). Child folders no longer show the project name, reducing noise.
* Add a toggle action to hide project names. This is available as a "secondary" action in a cog on the toolbar
> Improve Unity Explorer project name handling

- CHANGELOG.md
- resharper/resharper-unity/src/resharper-unity.resharper.nuspec
- rider/src/main/resources/META-INF/plugin.xml
Updated ReSharper nuspec with wave number, copyright and details. Also updated missing details in CHANGELOG.md and plugin.xml
> Update nuspec and changelogs

- rider/frontend.gradle
Loads annotations in Rider with latest SDK. ReSharper still uses the ReSharper extension ID (`Extensions\JetBrains.Unity\annotations`) and now Rider uses the Rider plugin ID (`Extensions/com.intellij.resharper.unity/annotations`)
> Use frontend plugin ID for extensions folder ID

- resharper/resharper-unity/src/CSharp/Daemon/Stages/Analysis/UnityEventFunctionAnalyzer.cs
- resharper/resharper-unity/src/CSharp/Daemon/Stages/Highlightings/IconsProviders/EventHandlerDetector.cs
- resharper/resharper-unity/src/CSharp/Daemon/Stages/Highlightings/IconsProviders/FieldDetector.cs
- resharper/resharper-unity/src/CSharp/Daemon/Stages/Highlightings/IconsProviders/TypeDetector.cs
- resharper/resharper-unity/src/CSharp/Daemon/Stages/Highlightings/UnityHighlightingAbstractStage.cs
- resharper/resharper-unity/src/CSharp/Daemon/Stages/Highlightings/UnityHighlightingContributor.cs
- resharper/resharper-unity/src/CSharp/Daemon/Stages/Highlightings/UnityHighlightingGlobalStage.cs
- resharper/resharper-unity/src/CSharp/Daemon/Stages/Highlightings/UnityHighlightingStage.cs
- resharper/resharper-unity/src/Rider/CSharp/Feature/Services/Bulbs/ShowUsagesInUnityBulbAction.cs
- resharper/resharper-unity/src/Rider/CodeInsights/RiderUnityHighlightingContributor.cs
- resharper/resharper-unity/src/Rider/UnityEditorFindUsageResultCreator.cs
- resharper/resharper-unity/src/Rider/UnityEditorOccurrence.cs
- resharper/resharper-unity/src/Settings/UnitySettings.cs
- resharper/resharper-unity/src/UnityApi.cs
- resharper/resharper-unity/src/Yaml/Psi/Modules/UnityYamlDisableStrategy.cs
- resharper/resharper-unity/src/Yaml/Rider/AssetModeNotification.cs
- resharper/resharper-unity/src/Yaml/Rider/Psi/Modules/RiderUnityYamlDisableStrategy.cs
- resharper/resharper-unity/src/Yaml/VisualStudio/Psi/Modules/ReSharperUnityYamlDisableStrategy.cs
- resharper/resharper-unity/test/data/CSharp/Daemon/Stages/GutterMark/resharper/Test01.cs.gold
- resharper/resharper-unity/test/data/CSharp/Daemon/Stages/GutterMark/rider/Test01.cs.gold
- rider/protocol/src/main/kotlin/model/rider/RdUnityModel.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/notifications/AssetModeForceTextNotification.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/ProcessesPanel.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorRunConfiguration.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorSettingsEditor.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorViewModel.kt
- rider/src/main/resources/META-INF/plugin.xml
1. "Show usages in Unity" Action is cancelable 
2.  "Show usages in Unity" executed on background thread 
3. Fix bug with attaching and entering playmode in different unity 
4. Add notification when "Show usages in Unity" is clicked and Unity asset mode is not "force text"
5. Do not create .dotSettings.user file when yaml heuristic is applied
6. Remove redundant code vision/highlightings for serializable types and fields
7. Remove "set by unity" for fields which are not in MonoBehaviour or Scriptable Object
8. Event function -> event handler for user functions
9. Do not suggest generate event function for non unity types
> UX improvement

- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/AssetsRoot.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/PackagesManager.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/PackagesRoot.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/ShowReferencePropertiesAction.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorer.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorerNode.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorerProjectModelViewUpdater.kt
This PR will:
Fixes #1095, fixes [RIDER-25971](https://youtrack.jetbrains.com/issue/RIDER-25971)
> Fix exception for file: and git based packages

- rider/build.gradle
- rider/buildSrc/build.gradle.kts
- rider/buildSrc/src/main/kotlin/com/jetbrains/rider/plugins/gradle/BackendPaths.kt
This gives us a green build on CI again
> Fix non-Windows build

- CHANGELOG.md
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/attach/UnityPlayer.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/attach/UnityProcessListener.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/attach/UnityProcessPickerDialog.kt
- rider/src/main/resources/META-INF/plugin.xml
Only lists the project name for players, which must be built with Unity 2019.2.
See #1009 to add project name to editor instances.
Also fixes minor UI issues - ESC will cancel the dialog if nothing is focussed, and Enter will accept the manual entry dialog while the port field is being edited.
> Add project name to list of debuggable players

- CHANGELOG.md
- resharper/resharper-unity/src/Yaml/Psi/Resolve/MonoScriptReference.cs
- resharper/resharper-unity/src/Yaml/Psi/Resolve/UnityEventTargetReference.cs
- resharper/resharper-unity/src/resharper-unity.resharper.nuspec
- rider/src/main/resources/META-INF/plugin.xml
> Fix YAML reference error and better handle rename

- resharper/resharper-unity/src/Yaml/Psi/Modules/UnityExternalFilesModuleFactory.cs
- resharper/resharper-unity/src/Yaml/Psi/Modules/UnityExternalFilesModuleProcessor.cs
- resharper/resharper-unity/src/Yaml/Psi/Modules/UnityYamlAssetPsiSourceFile.cs
- resharper/resharper-unity/src/Yaml/Psi/Modules/UnityYamlPsiSourceFileFactory.cs
- resharper/resharper-unity/src/Yaml/Psi/UnityYamlPsiSourceFileExtensions.cs
This PR fixes support for ReSharper for Find Usages, rename, etc. in YAML based asset files.
Rider requires that the external YAML files are added as project files, so we add them to the Misc Files project. This is because:
* Find Usages results requires a project item, or it will throw an exception
* SWEA only processes project files, and we want to be processed so that YAML usages of methods and classes is included in the Code Vision usage count metric
Unfortunately, ReSharper keeps the Misc Files project in sync with Visual Studio's view of the Misc Files project, which is limited to files currently open in the editor that aren't part of any other project. This means that our YAML files are removed from Misc Files and leaves orphaned PSI source files and causes lots of exceptions. …
> Fix ReSharper support for YAML asset files

- resharper/resharper-unity/src/Rider/CodeInsights/RiderUnityHighlightingContributor.cs
- resharper/resharper-unity/src/Rider/CodeInsights/UnityCodeInsightsHighlighting.cs
Show documentation in code vision tooltip for event functions
> Update tooltips for Unity code vision

- unity/EditorPlugin/OnOpenAssetHandler.cs
issue 21 in package
on mac empty string in quotes is causing additional solution to be opened https://github.cds.internal.unity3d.com/unity/com.unity.ide.rider/issues/21
Workarounds a bug on mac:
`open -n “//Users/user/Library/Application Support/JetBrains/Toolbox/apps/Rider/ch-2/191.7141.355/Rider.app” --args “/Users/user/Work/com.unity.ide.rider/com.unity.ide.rider.sln” --line -1 “”`
opes 2 solutions, where first is good and second one is
`/Users/user/Library/Application Support/JetBrains/Toolbox/apps/Rider/ch-2/191.7141.355/Rider.app/Contents/bin`
> on mac empty string in quotes is causing additional solution to be opened 

- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/attach/UnityRunUtil.kt
fix https://github.com/JetBrains/resharper-unity/issues/1283
> Add `Unity.Licensing.Client` to list of ignored processes

- CHANGELOG.md
- resharper/resharper-unity/src/resharper-unity.resharper.nuspec
- rider/src/main/resources/META-INF/plugin.xml
Updates `CHANGELOG.md` and `plugin.xml` with missing details from the 2019.2 release. Pushing this to the 2019.2.1 branch
> Update CHANGELOG for 2019.2.1

- CHANGELOG.md
- resharper/resharper-unity/src/CSharp/Feature/Services/CodeCompletion/UnityEventFunctionRule.cs
- resharper/resharper-unity/test/data/CSharp/CodeCompletion/List/AlphabeticalMonoBehaviour01.cs.gold
- resharper/resharper-unity/test/data/CSharp/CodeCompletion/List/DoNotListVirtualFunctions.cs.gold
- resharper/resharper-unity/test/data/CSharp/CodeCompletion/List/EditorWindow01.cs.gold
- resharper/resharper-unity/test/data/CSharp/CodeCompletion/List/MonoBehaviour01.cs.gold
- resharper/resharper-unity/test/data/CSharp/CodeCompletion/List/MonoBehaviour06.cs
- resharper/resharper-unity/test/data/CSharp/CodeCompletion/List/NoCompletionFollowingSerializeFieldAttribute01.cs.gold
- resharper/resharper-unity/test/data/CSharp/CodeCompletion/List/UnityEditor01.cs.gold
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/PackagesRoot.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorerNode.kt
- rider/src/main/resources/META-INF/plugin.xml
Currently, the contents of read only packages are highlighted as IGNORED in Unity Explorer, because they're cache in `Library`, which is usually ignored in VCS. Highlighting VCS status is irrelevant as they're read only.
> Show read only package files as unchanged

- unity/EditorPlugin/PluginEntryPoint.cs
- unity/EditorPlugin/PluginSettings.cs
> optimize performance

- CHANGELOG.md
- resharper/resharper-unity/src/resharper-unity.resharper.nuspec
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ContentModelUpdater.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/PackagesRoot.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorer.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorerNode.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorerProjectModelViewUpdater.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/notifications/UnityAutoSaveConfigureNotification.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/packageManager/PackageManager.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ui/UnityStatusBarIcon.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/FileUtils.kt
- rider/src/main/resources/META-INF/plugin.xml
> Migrate to async VFS file listeners

- CHANGELOG.md
- resharper/.idea/.idea.rider-unity/.idea/runConfigurations/runIde.xml
- resharper/.idea/.idea.rider-unity/.idea/runConfigurations/runIde__offline_.xml
- resharper/resharper-unity/src/ProjectModel/MetaFileTracker.cs
- rider/src/main/resources/META-INF/plugin.xml
Was hardcoded to Windows line endings (`\r\n`), but this can cause problems with Perforce on Mac, which does a dumb line conversion and ends up with `\r\r\n`.
> Use native line endings in .meta files

- CHANGELOG.md
- resharper/resharper-unity/src/Rider/MonoInstallTrigger.cs
- resharper/resharper-unity/src/resharper-unity.resharper.nuspec
- rider/src/main/resources/META-INF/plugin.xml
Fixes bug that meant that "Install Mono" notification wasn't shown on Mac for modern Unity projects and a modern Mono install does not exist.
> Fix Mono notification logic

- CHANGELOG.md
- resharper/resharper-unity/src/CSharp/Feature/Services/LiveTemplates/Rider/UnityLiveTemplatesOptionsPage.cs
- rider/src/main/kotlin/com/jetbrains/rider/settings/templates/UnityTemplatesOptionPage.kt
- rider/src/main/resources/META-INF/plugin.xml
This PR adds a "Unity" Live Templates page to match the existing File Templates page. All of the Unity specific Live Templates are already shown in the C# page, but it's hard to find them because the options pages don't list categories (all Unity templates have the "unity" category). A separate page can list them all.
> Add Unity specific Live Templates page

- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/UnityHost.kt
For some reason old version of code was failing locally on mac
> avoid loading Native.load("user32") on non-windows

- CHANGELOG.md
- rider/.idea/jarRepositories.xml
- rider/frontend.gradle
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/uss/UssDocumentationProvider.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/uss/UssFile.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/uss/UssFileBreadcrumbsProvider.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/uss/UssFileParserDefinition.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/uss/UssFileType.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/uss/UssLanguage.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/uss/UssSyntaxHighlighter.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/uss/codeInsight/css/UssCssElementDescriptorFactory.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/uss/codeInsight/css/UssCssElementDescriptorProvider.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/uss/codeInsight/css/inspections/UssCssInspectionFilter.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/uss/codeInsight/css/inspections/UssCssIntentionFilter.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/uss/readme.md
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/uxml/readme.md
- rider/src/main/resources/META-INF/plugin.xml
- rider/src/main/resources/uss/element-descriptors.xml
Adds initial support for USS files:
> Add initial USS file support

- resharper/resharper-unity/src/ProjectModel/MetaFileTracker.cs
fix RIDER-35227 Failed to create Unity meta file /usr/share/dotnet/sdk/3.0.100/Microsoft.Common.CurrentVersion.targets.meta
and
RIDER-35197 Opening json file from Library folder creates bogus meta file
> Avoid creating meta files in non-Unity projects

- CHANGELOG.md
- rider/src/main/resources/META-INF/plugin.xml
- unity/EditorPlugin/PluginEntryPoint.cs
- unity/EditorPlugin/UnityEventLogSender.cs
This PR works around a bug in Unity since at least 2017.1 that stops sending log events to subscribers when Unity leaves play mode. See [1102950](https://issuetracker.unity3d.com/issues/general-unityengine-dot-application-dot-logmessagereceived-is-not-being-raised-after-exiting-play-mode) on Unity's issue tracker. 
This bug affects 2017.1 and above (I didn't test 5.x), even though the bug report states 2017.4. The bug is closed as "by design" because changing it could break existing work arounds.
This PR also fixes an issue where the Unity log tool window was cleared when the pause state changed, rather than simply when entering play mode.
> Workaround Unity bug sending log events

- CHANGELOG.md
- resharper/resharper-unity/src/Yaml/Psi/Resolve/EventHandlerSymbolFilter.cs
- resharper/resharper-unity/src/Yaml/Psi/Resolve/UnityEventTargetReferenceFactory.cs
- resharper/resharper-unity/src/resharper-unity.resharper.nuspec
- rider/src/main/resources/META-INF/plugin.xml
Unity 2018.4 removed the `m_TypeName` serialised field, so we no longer know the type of custom `UnityEvent` based events. This PR makes the event handler resolve, but it can't confirm the method signature.
If we wanted to get the correct signature, we'd have to walk up the YAML, resolving types and types of fields until we could find the event type. There's a deeper explanation in the comments in `UnityEventTargetReferenceFactory.cs`.
Fixes #1448
> Fix resolving event based handlers for Unity 2018.4+

- resharper/resharper-unity/src/Rider/Packages/PackageValidator.cs
- resharper/resharper-unity/src/Rider/UnitTesting/RunViaUnityEditorStrategy.cs
fix for 
RIDER-36598 PlayMode tests for Unity 2019.1 are inconclusive and do not provide any help in the output
> Provide help message on failed PlayMode tests with old Unity

- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/FileExtensions.kt
When opening a file with no extension, e.g. `README`, an exception is thrown when checking to see if it's a known Unity file type. See [DEXP-497558](https://youtrack.jetbrains.com/issue/DEXP-497558). The exception is new to `net201` and doesn't reproduce in `net193`
> Fix null reference exception with file with no extension

- CHANGELOG.md
- resharper/resharper-unity/src/Feature/Internal/DumpDuplicateTypeNamesAction.cs
- resharper/resharper-unity/src/Settings/AutoImportSolutionSettingsProvider.cs
- resharper/resharper-unity/src/Settings/LangVersionProjectSettingsProvider.cs
- resharper/resharper-unity/src/Settings/NamespaceProviderProjectSettingsProvider.cs
- resharper/resharper-unity/src/resharper-unity.resharper.nuspec
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/actions/internal/DumpDuplicateTypeNamesAction.kt
- rider/src/main/resources/META-INF/plugin.xml
Adds `Boo.Lang.*` and `UnityScript.*` as namespaces to be excluded from auto-import. Also adds `System.Diagnostics.Debug` as a method to be ignored. This means that these namespaces and types are not shown in import completion popup lists, the auto-import tooltip popup, and any other quick fix. The only way to use these types is to manually add the using statement.
This addresses the issue that trying to complete `List<T>` can match `Boo.Lang.List<T>`.
This PR also adds an internal action to Rider that will dump all duplicate type names in a given project. Useful to show candidates that could use further rules.
Fixes #574
> Exclude conflicting type names from import completion

- resharper/resharper-unity/src/ProjectExtensions.cs
- resharper/resharper-unity/src/ProjectModel/MetaFileTracker.cs
fix https://github.com/JetBrains/resharper-unity/issues/1481
Repro:
1. Open Unity project in Rider
2. In SolutionExplorer show all files
3. Include any file outside Assets/Packages to project
Meta file was generated previously, not it would not.
> Avoid creating meta files outside Assets and Packages

- rider/build.gradle
Backport #1520 to `net193` in case there's another 2019.3 maintenance release
> Fix building searchable options (net193)

- rider/build.gradle
Backport #1520 to net193 in case there's another 2019.3 maintenance release
> Fix building searchable options

- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/UnityHost.kt
Was happening only with Windows Multitasking "Snap windows" setting is enabled
> fix RIDER-38427 - opening script resizes Rider

- resharper/resharper-unity/src/Rider/CodeInsights/UnityCodeInsightFieldUsageProvider.cs
- resharper/resharper-unity/src/Rider/RiderUnityAssetOccurrenceNavigator.cs
- resharper/resharper-unity/src/Yaml/Psi/DeferredCaches/AssetInspectorValues/AssetInspectorValuesContainer.cs
- resharper/resharper-unity/src/Yaml/Psi/DeferredCaches/AssetMethods/AssetMethodsElementContainer.cs
1. Show usages for inspector changes for derived classes in base classes
2. Update code vision presentation for that case
3. Find usage does not find wrong usages more for methods with same name to used methods
> Fixes for find usages & counters presentation

- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorRunConfiguration.kt
pid from protocol is usually better then pid stored in run-configuration.
I verified this fix helped on Windows, however on Mac there were exceptions
https://youtrack.jetbrains.com/issue/DEXP-516314 and https://youtrack.jetbrains.com/issue/DEXP-516333
reviewed by @krasnotsvetov
> fix DTRC-26621

- CHANGELOG.md
- resharper/resharper-unity/src/resharper-unity.resharper.nuspec
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/packageManager/PackageManager.kt
- rider/src/main/resources/META-INF/plugin.xml
Git based packages are not resolving properly in Unity 2019.3+. The format of the name of the cached package folder has changed - in Unity 2019.2, it's `{name}@{hash}`, while in 2019.3+, it only uses the first 10 characters of the hash.
> Fix resolving git packages for 2019.3+

- resharper/resharper-unity/src/Rider/UnityRefreshTracker.cs
Saves in the editor might be very frequent.
And each refresh may break completion https://youtrack.jetbrains.com/issue/RIDER-37420
From user logs:
> Avoid calling Refresh on every save in the editor

- CHANGELOG.md
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/AssetsRoot.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/PackagesRoot.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorerNode.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/packageManager/PackageManager.kt
- rider/src/main/resources/META-INF/plugin.xml
This PR fixes a few issues with the Unity Explorer:
> Minor fixes for the Unity Explorer

- CHANGELOG.md
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorerNode.kt
- rider/src/main/resources/META-INF/plugin.xml
`Assembly-CSharp.Player` was being shown as `.Player` in the Unity Explorer. Now shown as just `Player`. A player project that is not the default will show the full name, e.g. `Unity.Collections.Player`.
> Improve presentation of Player projects

- CHANGELOG.md
- resharper/resharper-unity/src/annotations/UnityEngine.CoreModule.xml
- resharper/resharper-unity/src/annotations/UnityEngine.xml
- resharper/resharper-unity/src/resharper-unity.resharper.nuspec
- rider/src/main/resources/META-INF/plugin.xml
Remove the `[BaseTypeRequired(typeof(MonoBehaviour))]` external annotation from the `ExecuteAlways` attribute. This attribute can be applied to types deriving from `MonoBehaviour`, but also from `Unity.Entities.SystemBase`, although this is not currently documented in the docs for `ExecuteAlways`.
> although I suppose ComponentSystemBase would be a better test since that would also cover ComponentSystem and JobComponentSystem variants
This PR comments out the annotation. It doesn't delete it so that we don't accidentally add it again. We don't have tests for annotations, and we especially don't have tests for absence of a warning.
See also #1639 about restoring this functionality but with a choice of base type between `MonoBehaviour` and `SystemBase`/`ComponentSystemBase`.
> Comment out annotation on ExecuteAlways

- CHANGELOG.md
- resharper/resharper-unity/src/CSharp/Feature/Services/QuickFixes/CreateStaticConstructorFromUsageAction.cs
- resharper/resharper-unity/src/resharper-unity.resharper.nuspec
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/RedundantInitializeOnLoadAttribute/Test05.cs
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/RedundantInitializeOnLoadAttribute/Test05.cs.gold
- resharper/resharper-unity/test/src/CSharp/Intentions/QuickFixes/RedundantInitializeOnLoadAttributeQuickFixTests.cs
- rider/src/main/resources/META-INF/plugin.xml
Fixes an issue where the "redundant `[InitializeOnLoad]`" quick fix would fail to generate a static constructor if member generation settings were set to "default return value".
> Correctly generate static constructor without body

- CHANGELOG.md
- resharper/resharper-unity/src/CSharp/Daemon/Stages/Analysis/RedundantAttributeOnTargetProblemAnalyzer.cs
- resharper/resharper-unity/src/CSharp/Daemon/Stages/Analysis/RedundantHideInInspectorAttributeProblemAnalyzer.cs
- resharper/resharper-unity/src/CSharp/Feature/Services/ContextActions/AddHeaderAttributeAction.cs
- resharper/resharper-unity/src/CSharp/Feature/Services/ContextActions/AddRangeAttributeAction.cs
- resharper/resharper-unity/src/CSharp/Feature/Services/ContextActions/AddSpaceAttributeAction.cs
- resharper/resharper-unity/src/CSharp/Feature/Services/ContextActions/AddTooltipAttributeAction.cs
- resharper/resharper-unity/src/CSharp/Feature/Services/ContextActions/CreateAssetMenuContextAction.cs
- resharper/resharper-unity/src/CSharp/Feature/Services/ContextActions/ToggleHideInInspectorAttributeAction.cs
- resharper/resharper-unity/src/CSharp/Psi/CodeAnnotations/CustomCodeAnnotationProvider.cs
- resharper/resharper-unity/src/KnownTypes.cs
- resharper/resharper-unity/src/resharper-unity.resharper.nuspec
- resharper/resharper-unity/test/data/CSharp/Psi/CodeAnnotations/RangeAttributeAsValueRangeAttribute.cs
- resharper/resharper-unity/test/data/CSharp/Psi/CodeAnnotations/RangeAttributeAsValueRangeAttribute.cs.gold
- resharper/resharper-unity/test/src/CSharp/Psi/CodeAnnotations/CustomCodeAnnotationProviderTest.cs
- resharper/resharper-unity/test/src/CSharp/Psi/CodeAnnotations/FixCharacterControllerCollisionFlagAnnotationTests.cs
- resharper/resharper-unity/test/src/TestEnvironment.cs
- rider/src/main/resources/META-INF/plugin.xml
ReSharper/Rider 2020.1 introduced integer value dataflow analysis, which can track the value of integers through a piece of code. The `ValueRange` attribute can provide a hint that an integer value is only between a min and max value.
Unity's `Range` attribute can be applied to fields, and the Inspector will ensure that the value of the field is kept between the given min and max value.
This PR will map Unity's `Range` attribute to ReSharper's `ValueRange` annotation, using the `Range`'s min/max values as the hint to ReSharper's dataflow analysis. Note that ReSharper's analysis only works with integer values, so `Range` attributes on float values are ignored.
> Map range attribute to value range annotation

- CHANGELOG.md
- resharper/resharper-unity/src/Settings/NamespaceProviderProjectSettingsProvider.cs
- resharper/resharper-unity/src/resharper-unity.resharper.nuspec
- resharper/resharper-unity/src/rider-unity.csproj
- rider/src/main/resources/META-INF/plugin.xml
Add new rules to disable the "namespace provider" for the following folders. This will stop Rider/ReSharper from suggesting that folder as part of the namespace name. Once this PR is applied, the following folders will no longer be included in namespace name suggestions:
* `Assets`
* `Assets/Scripts`
* `Packages/<package-root>` - any top level folder under `Packages`
* `Packages/<package-root>/**` - any non-project folders. I.e. any folder under a package root that does not have `package.json`
* `Packages/<package-root>/**/Runtime`
* `Packages/<package-root>/**/Scripts`
* `Packages/<package-root>/**/Runtime/Scripts`
* `Packages/<package-root>/**/Scripts/Runtime`
* `Library/PackageCache/<package-root>`
* `Library/PackageCache/<package-root>/**` - any non-project folders. I.e. any folder …
> Disable namespace provider for Packages and subfolder

- CHANGELOG.md
- resharper/resharper-unity/src/CSharp/Psi/Util/ExternalPackageCustomNamespaceProvider.cs
- resharper/resharper-unity/src/Settings/NamespaceProviderProjectSettingsProvider.cs
- resharper/resharper-unity/src/resharper-unity.resharper.nuspec
- rider/src/main/resources/META-INF/plugin.xml
This PR expands on #1677 to support correct namespace suggestions for packages that are outside of the normal Unity project structure and included via `file:` references in `Packages/manifest.json`. It handles projects that live under the normal Unity project folder location (but not under `Assets` or `Packages`) and also projects outside of the solution structure completely.
To recap, the idea is this:
* A package owner has no control over the location of a package, or the name of its root folder, so these things should not affect the namespace of the code. (E.g. a package can live in `Packages`, `Library/PackageCache` or anywhere else on disk, and when under `Library/PackageCache`, the name can contain ID and version, but won't have this name when cloned from GitHub)
* An assembly …
> Handle namespace suggestions for external packages 

- CHANGELOG.md
- debugger/src/debugger.csproj
- resharper/resharper-unity/src/Rider/Host/DebuggerOutputAssemblies/UnityDebuggerOutputAssembliesProviderHost.cs
- rider/src/main/resources/META-INF/plugin.xml
Unity doesn't use the assemblies compiled to the C# project output path of `Temp/Bin/Debug/`. It controls compilation and saves the assemblies (possibly with IL rewriting) in `Library/ScriptAssemblies`. If the C# project has not been built, all user code is treated as library code.
This PR treats any project output that also exists in `Library/ScriptAssemblies` as user code.
Fixes #1671
> Treat Unity's compiled assemblies as user code

- .github/workflows/ci.yml
Make sure we only use known `gradle-wrapper.jar` files before they get invoked as part of the build.
> Validate gradle-wrapper.jar before running GH workflows

- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/PackagesRoot.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorer.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorerNode.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ide/navigationToolbar/UnityNavBarModelExtension.kt
- rider/src/main/resources/META-INF/plugin.xml
This PR will:
* Unify the "show all files" setting between Unity Explorer and Solution Explorer
* Filter out `.meta` files from the navigation bar, as they introduce too much noise. They can be shown again with the "show all files" setting.
Fixes [RIDER-28425](https://youtrack.jetbrains.com/issue/RIDER-28425)
> Hide .meta files from navigation bar

- CHANGELOG.md
- resharper/resharper-unity/src/CSharp/Psi/CodeAnnotations/CustomCodeAnnotationProvider.cs
- resharper/resharper-unity/src/KnownTypes.cs
- resharper/resharper-unity/test/data/CSharp/Psi/CodeAnnotations/MinAttributeAsValueRangeAttribute.cs
- resharper/resharper-unity/test/data/CSharp/Psi/CodeAnnotations/MinAttributeAsValueRangeAttribute.cs.gold
- resharper/resharper-unity/test/src/CSharp/Psi/CodeAnnotations/CustomCodeAnnotationProviderTest.cs
Similar to #1673, this uses Unity's `MinAttribute` to create a custom/dynamic `ValueRange` annotation for data flow analysis.
> Use MinAttribute as ValueRange provider

- resharper/resharper-unity/src/CSharp/Daemon/Stages/Highlightings/UnityHighlightingAttributeIds.cs
- resharper/resharper-unity/src/CSharp/Psi/CodeStyle/Resources/AdditionalFileLayoutPatterns.xaml
- resharper/resharper-unity/src/CSharp/Psi/CodeStyle/Resources/AdditionalFileLayoutPatternsWithRegions.xaml
- resharper/resharper-unity/src/CSharp/Psi/CodeStyle/Settings/Rider/AdditionalFileLayoutSettingsHelper.cs
- resharper/resharper-unity/src/CSharp/Psi/CodeStyle/Settings/Rider/UnityFileLayoutPageTab.cs
- resharper/resharper-unity/src/rider-unity.csproj
- resharper/resharper-unity/src/rider-unity.csproj.DotSettings
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/settings/fileLayout/AdditionalFileLayoutOptionsPage.kt
- rider/src/main/resources/META-INF/plugin.xml
Moves the Unity file layout options page to be a tab, as part of the main C# file layout settings.
Also fixes a minor UI issue, removing the performance critical line marker from the demo text in the Unity colour schemes options page (was rendering as a nasty orange background, instead of the expected line marker).
> Improve discoverability of Unity file layout settings

- debugger/debugger-worker/src/Values/Render/ValuePresenters/ExternalDebuggerDisplayObjectPresenter.cs
- debugger/ios-list-usb-devices/src/Program.cs
- debugger/ios-list-usb-devices/src/ios-list-usb-devices.csproj
- rider/frontend.gradle
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/AppleDeviceListener.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/UnityProcessPickerDialog.kt
Fixes the _Attach to Unity Process_ dialog, which broke on Mac/Linux due to removing Mono backend.
* Catches exceptions spawning the helper exe, so failure to execute no longer break the whole dialog
* Create a .net core version of the `iOS-list-usb-devices` project for Mac/Linux. EAP7 will remove the bundled Mono, so we need a .net core version. Rider will bundle .net core 3.1 for Mac/Linux, but not for Windows, so we use the net461 version on Windows.
* Update the _Attach to Unity Process_ dialog to execute the correct version of the helper exe
* Fix the helper exe on Windows failing to find any iOS devices over USB due to calling into a native library that uses sockets but which doesn't initialise the WinSock API. Creating a `Socket` in managed code and immediately disposing it is …
> Fix Attach to Unity process dialog not showing

- resharper/resharper-unity/src/Rider/UnityRefreshTracker.cs
exception on Refresh in Unity 2017.x
> fix DEXP-527982

- unity/EditorPlugin/PluginEntryPoint.cs
- unity/EditorPlugin/UnityEventLogSender.cs
I need a repro of the lock to test this.
> Workaround for debugger evaluation timeout

- .gitignore
- CHANGELOG.md
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/PackagesRoot.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/packageManager/PackageData.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/packageManager/PackageManager.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/UnityCachesFinder.kt
- rider/src/main/kotlin/icons/UnityIcons.kt
Unity 2019.4+ has moved git hash details from `manifest.json` and into a new `packages-lock.json`. This file contains a full graph of packages, including transitive dependencies.
This PR:
* Reads package details from `packages-lock.json` if it exists, falling back to `manifest.json` ([RIDER-47191](https://youtrack.jetbrains.com/issue/RIDER-47191))
* Supports local tarball packages (the manifest references a `package.tgz` file with the package expanded to `Library/PackageCache`) (#1589)
* Supports `UPM_CACHE_PATH` environment variable for fallback to global package cache (#1766)
> Support git packages in Unity 2019.4+

- resharper/resharper-unity/src/HlslSupport/Feature/Services/TypingAssists/InjectedHlslDummyFormatter.cs
- resharper/resharper-unity/src/HlslSupport/Integration/Cpp/InjectedHlslInclusionContextProvider.cs
- resharper/resharper-unity/src/HlslSupport/Integration/Cpp/UnityGameEngineDirectiveResolver.cs
Fixes the transformation of shader include file paths to package cache folders when the package cache contains packages that don't have a version, such as git based packages, where the filename is based on `{name}@{commit-hash}` rather than `{name}@{version}`.
> Handle non-version suffixes in package cache for shader includes

- debugger/debugger-worker/src/Values/Render/ChildrenRenderers/ScenePathValueHelper.cs
The debugger extensions adds a "Scene Path" value to `Component` and `GameObject` instances. If the game object's `transform` is a `RectTransform` instead of just a `Transform` instance, we fail to find the `Transform.root` property. This PR changes behaviour to search in base classes too.
> Fix missing "Scene Path" value in debugger

- resharper/resharper-unity/src/HlslSupport/Integration/Cpp/InjectedHlslInclusionContextProvider.cs
- resharper/resharper-unity/src/HlslSupport/Integration/Cpp/UnityGameEngineDirectiveResolver.cs
- resharper/resharper-unity/src/HlslSupport/Integration/Cpp/UnityHlslCppCompilationPropertiesProvider.cs
- resharper/resharper-unity/src/HlslSupport/Integration/Injections/InjectedHlslFileLocationTracker.cs
- resharper/resharper-unity/src/Templates/File/StandardSurfaceShader.md
1) fix include path resolving for Mac OS(use relative paths instead o…f absolute, because R++ engine considers paths which are started from separator as special paths)
2) fix include resolving for local packages (fix RIDER-48210)
3) fix template for surface shader RIDER-48073
> Fixes for Shader support

- CHANGELOG.md
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/packageManager/PackageManager.kt
> Minor package explorer fixes

- CHANGELOG.md
- apiParser/src/Program.cs
- resharper/resharper-unity/src/UnityEventFunction.cs
- resharper/resharper-unity/src/UnityType.cs
- resharper/resharper-unity/src/Utils/VersionEx.cs
- resharper/resharper-unity/src/api.xml
- resharper/resharper-unity/test/src/VersionExTests.cs
Rider 2020.2 updated API information for `ScriptableObject.OnValidate`. It is undocumented up to Unity 2020.1, and documented from Unity 2020.2. The implementation of `Version.CompareTo` will treat missing build and revision numbers as older, so a maximum API version of 2020.1 is less than the product version of 2020.1.1, and since this is also less than 2020.2, Rider does not find a record for `ScriptableObject.OnValidate`.
This change introduces an extension method for `Version` - `CompareToLenient`. This will only compare the components of both versions that are defined, so `2020.1` is considered equal to `2020.1.1`. This fixes the issue for `ScriptableObject.OnValidate`.
Fixes [RIDER-49130](https://youtrack.jetbrains.com/issue/RIDER-49130)
> Compare API versions ignoring missing build numbers

- rider/backend.gradle
- rider/build.gradle
- rider/frontend.gradle
- rider/gradle.properties
> Fix minor issues with changelog notes

- resharper/resharper-unity/src/Rider/UnitTesting/UnityTaskRunnerHostController.cs
- resharper/resharper-unity/src/Rider/UnityController.cs
Fix run/debug NUnit tests when they don't run/debug for Unity
Fix exception "Illegal scheduler for current action.." when calling "UnityModel.Value.ExitUnity.Start"
Increase ourUnityConnectionTimeout
> Fix run/debug NUnit tests when they don't run/debug for Unity

- resharper/resharper-unity/src/resharper-unity.csproj
- resharper/resharper-unity/src/rider-unity.csproj
Will run Live Templates compiler before other PrepareResources targets, hopefully fixing a file exception if resgen runs first
> Update templates compiler version

- CHANGELOG.md
- resharper/resharper-unity/src/CSharp/Feature/Services/QuickFixes/ConvertToGameObjectAddComponentQuickFix.cs
- resharper/resharper-unity/src/CSharp/Feature/Services/QuickFixes/QuickFixRegistrar.cs
- resharper/resharper-unity/src/CSharp/Feature/Services/QuickFixes/RemoveRedundantAttributeQuickFix.cs
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/RedundantEventFunction/Availability/Test01.cs
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/RedundantEventFunction/Availability/Test01.cs.gold
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/RedundantEventFunction/Availability/Test02.cs
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/RedundantEventFunction/Availability/Test02.cs.gold
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/RedundantEventFunction/Availability/Test03.cs
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/RedundantEventFunction/Availability/Test03.cs.gold
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/RedundantEventFunction/Test01.cs
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/RedundantEventFunction/Test01.cs.gold
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/RedundantEventFunction/Test02.cs
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/RedundantEventFunction/Test02.cs.gold
- resharper/resharper-unity/test/src/CSharp/Intentions/QuickFixes/RedundantEventFunctionQuickFixTests.cs
Accidentally removed while converting actions to bulk fixes that use code cleanup.
> Fix missing redundant event function quick fix

- CHANGELOG.md
- resharper/resharper-unity/src/CSharp/Psi/UnityCSharpDeclaredElementPresenter.cs
- resharper/resharper-unity/test/data/CSharp/Daemon/IdentifierTooltip/EventFunction01.gold
- resharper/resharper-unity/test/data/CSharp/Daemon/IdentifierTooltip/EventFunction01.richText.gold
- resharper/resharper-unity/test/data/CSharp/Daemon/IdentifierTooltip/EventFunction02.gold
- resharper/resharper-unity/test/data/CSharp/Daemon/IdentifierTooltip/EventFunction02.richText.gold
- resharper/resharper-unity/test/data/CSharp/Daemon/IdentifierTooltip/EventFunctionWithGutterIcon01.gold
- resharper/resharper-unity/test/data/CSharp/Daemon/IdentifierTooltip/EventFunctionWithGutterIcon01.richText.gold
- resharper/resharper-unity/test/data/CSharp/Daemon/IdentifierTooltip/EventFunctionWithGutterIcon02.gold
- resharper/resharper-unity/test/data/CSharp/Daemon/IdentifierTooltip/EventFunctionWithGutterIcon02.richText.gold
- resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/RedundantEventFunctionWarning.cs.gold
- resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/resharper/HiddenEventFunctions.cs.gold
- resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/rider/HiddenEventFunctions.cs.gold
- resharper/resharper-unity/test/data/CSharp/Daemon/UsageChecking/MonoBehaviourFields01.gold
- resharper/resharper-unity/test/data/CSharp/Daemon/UsageChecking/MonoBehaviourMethods01.gold
- resharper/resharper-unity/test/data/CSharp/Daemon/UsageChecking/SerializableClassFields01.gold
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/InvalidSignature/Availability/AddMissingParameterThreeParameters_000.cs.gold
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/InvalidSignature/Availability/AddMissingParameterThreeParameters_010.cs.gold
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/InvalidSignature/Availability/AddMissingParameterThreeParameters_011.cs.gold
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/InvalidSignature/Availability/AddMissingParameterThreeParameters_100.cs.gold
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/InvalidSignature/Availability/AddMissingParameterThreeParameters_101.cs.gold
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/InvalidSignature/Availability/AddMissingParameterThreeParameters_110.cs.gold
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/InvalidSignature/Availability/ReorderParametersThreeParameters_132.cs.gold
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/InvalidSignature/Availability/ReorderParametersThreeParameters_213.cs.gold
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/InvalidSignature/Availability/ReorderParametersThreeParameters_231.cs.gold
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/InvalidSignature/Availability/ReorderParametersThreeParameters_312.cs.gold
- resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/InvalidSignature/Availability/ReorderParametersThreeParameters_321.cs.gold
Use Unity terminology in tooltip and other descriptions for serialised fields and event functions. This will also use "serialised field" and "event function" in descriptions for code analysis and quick fixes, such as "Event function is not used" and "Remove unused event function".
> Use Unity entity kind in element descriptions

- CHANGELOG.md
- resharper/resharper-unity/src/api.xml
- resharper/resharper-unity/test/data/CSharp/CodeCompletion/List/EditorWindow01.cs.gold
- resharper/resharper-unity/test/data/CSharp/Generate/HasExistingBaseFunctions.cs.gold
- resharper/resharper-unity/test/data/CSharp/Generate/ListElements09.cs.gold
Updates the API information to 2020.2.0b12. Also reruns the update for 2019.4.15f1 and 2020.1.14f1.
Adds the `EditorWindow.CreateGUI` message that was introduced in 2019.4. We did run the update on the docs from 2019.4.4f1, but for some reason, this message wasn't included. I have no idea why - rerun the update on 2019.4.4f1 and there it is! Go figure.
> Update API information

- CHANGELOG.md
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/actions/StartUnityAction.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorProfileState.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorRunConfiguration.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/UnityUtils.kt
has approval from @citizenmatt https://jetbrains.slack.com/archives/C53QFRZ7G/p1607095827243400?thread_ts=1607095038.241700&cid=C53QFRZ7G
> fix RIDER-54917 Profiling Unity from Rider forces `DebugCodeOptimization`

- CHANGELOG.md
- rider/gradle.properties
- unity/EditorPlugin/EditorPrefsWrapper.cs
- unity/EditorPlugin/PluginEntryPoint.cs
- unity/EditorPlugin/PluginSettings.cs
- unity/EditorPlugin/UnityUtils.cs
Stops subscribing to handle locking assemblies during play mode for Unity 2018.2+ where it's handled natively. This has the side effect of not accessing a legacy editor setting, which outputs a log message ([RIDER-55362](https://youtrack.jetbrains.com/issue/RIDER-55362)). The change stops subscribing to the `EditorApplication.playmodeStateChanged` event for Unity 2018.2+ as the functionality is now redundant - `PluginSettings.AssemblyReloadSettings` always returns `RecompileAndContinuePlaying` in this case.
> Fix debug message complaining about accessing old setting

- CHANGELOG.md
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ContentModelUpdater.kt
If the `Packages` folder contains any project code, it wasn't being explicitly indexed, so `Packages/manifest.json` wasn't added to the content model, and would show the "non-project file" dialog when trying to modify. If the `Packages` folder doesn't contain any project, it was being explicitly added, so the dialog wasn't shown. I don't know why `Packages` wasn't being indexed, because with the same code, `Assets` was indexed.
Note that this code will be rewritten soon, when the new project model is merged. It's still worth fixing now, to make sure that the rewritten version also correctly indexes both `Assets` and `Packages`.
> Ensure Packages folder is indexed

- resharper/resharper-unity/src/ProjectModel/MetaFileTracker.cs
1. avoid meta files in direct children of Packanges folder
2. support local package linked by relative path
> Improvements of old MetaFileTracker

- CHANGELOG.md
- resharper/resharper-unity/src/Feature/Services/ExternalSources/ZoneMarker.cs
- rider/gradle.properties
When running with the Unity plugin, `inspectcode` throws an exception because a schema setting entry isn't loaded, as its owning zone (`ExternalSourcesZone`) is not enabled for the command line runner.
> Add zone marker to fix exceptions in inspectcode

- resharper/resharper-unity/src/CSharp/Daemon/Stages/Highlightings/VisualStudio/UnityImplicitlyUsedIdentifierClassificationDefinition.cs
Doesn't make much difference. Just means that if someone changes the colours for "ReSharper all languages Default Identifier" in Visual Studio, then the "Unity Implicitly Used Identifier" will match. Previously, it would use the generic text colours.
> Use default identifier as base for ReSharper highlight

- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/uxml/codeInsight/schema/UxmlSchemaProvider.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/packageManager/PackageManager.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/quickDoc/UnityDocumentationProvider.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/attach/UnityLocalAttachProcessDebuggerProvider.kt
https://github.com/JetBrains/resharper-unity/issues/2005
requires some more testing.
https://docs.unity3d.com/2021.1/Documentation/ScriptReference/30_search.html?q=InitializeOnLoadAttribute
Version before 2017.1 has different format of version:
https://docs.unity3d.com/550/Documentation/ScriptReference/30_search.html?q=InitializeOnLoadAttribute
In the old version UI there is no goo way to change version. Clicking "current version" clears the seach term from the url.
> Make doc search link version specific

- CHANGELOG.md
- resharper/resharper-unity/src/ProjectModel/MetaFileTracker.cs
- resharper/resharper-unity/src/ProjectModel/UnitySolutionTracker.cs
This PR fixes two issues, mostly related to `.meta` file tracking and updating:
> Fix meta files not being updated

- CHANGELOG.md
- resharper/resharper-unity/src/ProjectModel/MetaFileTracker.cs
Hidden assets, such as those ending with `~` or starting with `.` are not imported into the asset database, and should not have a `.meta` file created. See the list of "Hidden Assets" on this page for [special folder names](https://docs.unity3d.com/Manual/SpecialFolders.html).
> Stop creating meta files for hidden assets

- CHANGELOG.md
- resharper/resharper-unity/src/CSharp/Feature/Services/CodeCompletion/UnityEventFunctionBehavior.cs
- resharper/resharper-unity/src/CSharp/Feature/Services/CodeCompletion/UnityEventFunctionRule.cs
- resharper/resharper-unity/test/data/CSharp/CodeCompletion/Action/RetypeFullNameOnExistingMethod01.cs
- resharper/resharper-unity/test/data/CSharp/CodeCompletion/Action/RetypeFullNameOnExistingMethod01.cs.gold
- resharper/resharper-unity/test/data/CSharp/CodeCompletion/Action/RetypeFullNameOnExistingMethod02.cs
- resharper/resharper-unity/test/data/CSharp/CodeCompletion/Action/RetypeFullNameOnExistingMethod02.cs.gold
- resharper/resharper-unity/test/src/CSharp/Feature/Services/CodeCompletion/UnityEventFunctionCompletionActionTest.cs
When editing the name of a function in a Unity class, if the name is being completely replaced, e.g. changing `Awake` to `Start` then the auto-completion for event functions will generate incorrect code. It will generate a new body for the event function, while the existing body is still there, resulting in something like:
```
public void Awake()
{
}
()
{
// Existing code
}
```
> Fix completion when replacing entire method name

- resharper/resharper-unity/test/src/app.config
- resharper/resharper-unity/test/src/tests.rider-unity.csproj
- resharper/resharper-yaml/test/src/app.config
- resharper/resharper-yaml/test/src/tests.rider-yaml.csproj
- rider/buildSrc/build.gradle.kts
Updates gradle-intellij-plugin to 0.7.2 to fix downloading the JBR. The old version had the wrong URL. Also fixes compile time warnings for assembly version resolution.
> Minor build fixes

- resharper/resharper-unity/src/Settings/Rider/ShowMarkerOnStaticMethodSettings.cs
Hide run-markers, because for Unity projects this wouldn't work.
For Unity we have `UnityRunMarkerProvider` instead.
https://youtrack.jetbrains.com/issue/RIDER-55734
> Disable ShowMarkerOnStaticMethods for Unity projects

- CHANGELOG.md
- debugger/debugger-worker/src/Evaluation/EvaluatorExceptionThrownExceptionHelper.cs
- debugger/debugger-worker/src/Evaluation/UnityAdditionalValuesProvider.cs
- debugger/debugger-worker/src/LoggerHelper.cs
- debugger/debugger-worker/src/Values/ChunkedValueGroupBase.cs
- debugger/debugger-worker/src/Values/Render/ChildrenRenderers/ComponentChildrenRenderer.cs
- debugger/debugger-worker/src/Values/Render/ChildrenRenderers/FilteredObjectChildrenRendererBase.cs
- debugger/debugger-worker/src/Values/Render/ChildrenRenderers/GameObjectChildrenRenderer.cs
- debugger/debugger-worker/src/Values/Render/ChildrenRenderers/ScenePathValueHelper.cs
- debugger/debugger-worker/src/Values/Render/ChildrenRenderers/SceneRootChildrenRenderer.cs
- debugger/debugger-worker/src/Values/Render/ChildrenRenderers/SerialisedPropertyChildrenRenderer.cs
- debugger/debugger-worker/src/Values/Render/ChildrenRenderers/SerializedObjectChildrenRenderer.cs
- debugger/debugger-worker/src/Values/Render/ValuePresenters/ExternalDebuggerDisplayObjectPresenter.cs
- debugger/debugger-worker/src/Values/Render/ValuePresenters/SerializedPropertyPresenter.cs
- debugger/debugger-worker/src/Values/ValueGroupBase.cs
- debugger/debugger-worker/src/Values/ValueReferences/CalculatedValueReferenceDecorator.cs
- debugger/debugger-worker/src/Values/ValueReferences/ValueReferenceDecoratorBase.cs
- rider/frontend.gradle
- rider/gradle.properties
This PR handles a number of exceptions generated while evaluating extra data such as "Active Scene", "this.gameObject", "Scene Path" and so on.
> Fix exceptions in debugger extension

- CHANGELOG.md
- debugger/ios-list-usb-devices/src/runtimeconfig.template.json
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/AppleDeviceListener.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/UnityPlayerListener.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/UnityProcessPickerDialog.kt
This PR fixes several issues with the "Attach to Unity Process" debug dialog:
> Fix issues with USB debugging + debug dialog

- CHANGELOG.md
- resharper/resharper-unity/src/CSharp/Feature/Services/LiveTemplates/Scope/MustBeInProjectWithUnityVersion.cs
The AsmDef file template uses the `MustBeInProjectWithUnityVersion` scope point that is parameterised with a Unity version. The default value is `2017.3`, because that's the first version that supported `.asmdef` files. Unfortunately, saving the template tries to save the scope point with the version serialised in 3 parts (`major.minor.build`) and if there are only 2 parts (`2017.3`) then it will throw an exception and the macros aren't saved.
This is a problem if the file template is modified to add a macro - the text content is saved, but the macro isn't. When evaluating, the macro placeholder is left in place. See [RIDER-61376](https://youtrack.jetbrains.com/issue/RIDER-61376)
> Fix exception when saving AsmDef file template

- CHANGELOG.md
- rider/gradle.properties
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/workspace/UnitySolutionManagerExtensions.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/workspace/UnityWorkspaceModelUpdater.kt
> Fixes for additional content roots in workspace model

- CHANGELOG.md
- resharper/resharper-unity/src/Packages/PackageManager.cs
We want to update the list of packages when `manifest.json` and/or `packages-lock.json` is modified. We prefer `packages-lock.json` because it's more accurate. So if the user modifies `manifest.json`, we want to wait to allow Unity the chance to resolve packages and update the lock file.
This PR simplifies the existing code. If `manifest.json` is modified, it fires a longer event before refreshing, to allow Unity a chance to update. If Unity doesn't update, the event still fires and we work with `manifest.json`. If Unity does update, we cancel the long event and update with the more accurate `packages-lock.json`.
This fixes [RIDER-62558](https://youtrack.jetbrains.com/issue/RIDER-62558) which hit an infinite loop in the old implementation, because if Unity isn't running, the file …
> Improve refreshing packages when manifest.json is newer than packages.json

- resharper/resharper-unity/src/CSharp/Feature/Services/LiveTemplates/Scope/UnityProjectScopeProvider.cs
- resharper/resharper-unity/src/ProjectModel/ProjectExtensions.cs
- resharper/resharper-unity/src/Yaml/Psi/Modules/UnityExternalFilesModuleProcessor.cs
https://jetbrains.slack.com/archives/C53QFRZ7G/p1620924775194600
When we have asmdef with Editor
"includePlatforms": [
"Editor",
],
UNITY_EDITOR define is in the csproj
Otherwise - when asmdef either exсludes Editor or doesn't include it - UNITY_EDITOR define is not in the csproj
"excludePlatforms": [
"Editor"
]
Assembly-CSharp and Assembly-CSharp-firstpass contain UNITY_EDITOR define, however Editor api-s compilation would fail.
If Player projects generation is enabled - those Player projects would not contain UNITY_EDITOR define.
> Allow Editor templates for projects with UNITY_EDITOR define

- resharper/resharper-unity/src/HlslSupport/ZoneMarker.cs
- resharper/resharper-unity/src/Rider/Shaders/ZoneMarker.cs
- resharper/resharper-unity/src/app.config
- resharper/resharper-unity/src/rider-unity.csproj
- resharper/resharper-unity/test/src/CSharp/Psi/CodeStyle/FileLayoutTests.cs
- resharper/resharper-unity/test/src/HackTestDataInNugets.cs
- resharper/resharper-unity/test/src/RequireHlslSupportAttribute.cs
- resharper/resharper-unity/test/src/ShaderLab/Daemon/Hlsl/HlslCodeAnalysisTest.cs
- resharper/resharper-unity/test/src/ShaderLab/Feature/Services/TypingAssist/ShaderLabTypingAssistTest.cs
- resharper/resharper-unity/test/src/TestEnvironment.cs
- resharper/resharper-unity/test/src/app.config
- resharper/resharper-unity/test/src/tests.resharper-unity.csproj
- resharper/resharper-unity/test/src/tests.rider-unity.csproj
- resharper/resharper-yaml/test/src/HackTestDataInNugets.cs
- resharper/resharper-yaml/test/src/TestEnvironment.cs
- resharper/resharper-yaml/test/src/app.config
Fixes a number of issues to get testing working again on Mac/Linux:
I haven't tested on Linux, but it should have the same behaviour as Mono on Mac.
> Update plugin testing on Mac/Linux

- CHANGELOG.md
- resharper/resharper-unity/src/Rider/CSharp/Feature/Services/QuickFixes/SceneManagerLoadSceneEnableQuickFix.cs
- resharper/resharper-unity/src/Rider/CSharp/Feature/Services/QuickFixes/SceneManagerLoadSceneQuickFix.cs
- resharper/resharper-unity/src/Yaml/Psi/Caches/EditorBuildSettingsAssetHandler.cs
- resharper/resharper-unity/src/Yaml/Psi/Caches/InputManagerAssetHandler.cs
- resharper/resharper-unity/src/Yaml/Psi/Caches/MetaFileGuidCache.cs
- resharper/resharper-unity/src/Yaml/Psi/Caches/TagManagerAssetHandler.cs
- resharper/resharper-unity/src/Yaml/Psi/Caches/UnityProjectSettingsUtils.cs
- resharper/resharper-unity/src/Yaml/Psi/DeferredCaches/AnimationEventsUsages/AnimationExtractor.cs
- resharper/resharper-unity/src/Yaml/Psi/DeferredCaches/AnimatorUsages/AnimatorExtractor.cs
- resharper/resharper-unity/src/Yaml/Psi/DeferredCaches/AnimatorUsages/AnimatorScriptUsagesElementContainer.cs
- resharper/resharper-unity/src/Yaml/Psi/DeferredCaches/AssetHierarchy/AssetDocumentHierarchyElementContainer.cs
- resharper/resharper-unity/src/Yaml/Psi/DeferredCaches/AssetInspectorValues/AssetInspectorValuesContainer.cs
- resharper/resharper-unity/src/Yaml/Psi/DeferredCaches/AssetScriptUsages/AssetScriptUsagesElementContainer.cs
- resharper/resharper-unity/src/Yaml/Psi/DeferredCaches/AssetUtils.cs
- resharper/resharper-unity/src/Yaml/Psi/DeferredCaches/UnityEvents/UnityEventsElementContainer.cs
- resharper/resharper-unity/src/Yaml/Psi/UnityYamlPsiExtensions.cs
- resharper/resharper-yaml/src/Psi/PsiExtensions.cs
Add support for the old format of `TagManager.asset` where layers were stored as individual properties (`Builtin Layer 0` - `Builtin Layer 7` and `User Layer 8` - `User Layer 31`) instead of as a simple array.
Also refactors the helper methods for working with the YAML PSI and Unity specific PSI helpers.
> Support v1 format for TagManager.asset

- CHANGELOG.md
- debugger/debugger-worker/src/Exceptions/UnityUnhandledExceptionHandler.cs
The Unity 2021.2 beta has an upgraded Mono which now reports unhandled exceptions to the debugger. The previous Mono version (~5.12ish) didn't report unhandled exceptions. This old behaviour does not appear to be deliberate or intentional, and it's not yet clear if this behaviour will be rolled back or not.
However, it has the consequence that the debugger will now frequently stop on unhandled `ExitGUIException`s. These are used as control flow exceptions, thrown in managed code and caught in native code (and therefore considered "unhandled" by Mono and Rider) in order to cancel behaviour in the GUI. The exception is thrown frequently as the user works with the Inspector and other windows, and makes using the Unity editor while debugging very annoying. This PR will ignore any unhandled …
> Prevent break on unhandled ExitGUIException

- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/actions/ShowFileInUnityAction.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ui/NonUserEditableEditorNotification.kt
- unity/.editorconfig
- unity/EditorPlugin/AfterUnity56/Navigation/Initialization.cs
This action "Show in Unity" can be called directly on current active file via Shift-Shift or for some files we show a notification in the editor with link to "Show in Unity" action.
This PR fixes the action for local packages and also avoids showing a link in notification for "meta" files.
> Fix "Show in Unity" for local packages

- resharper/resharper-unity/src/CSharp/Feature/Services/Navigation/GoToUnityUsages/GoToUnityUsagesProvider.cs
- resharper/resharper-unity/src/annotations/UnityEngine.TestRunner.xml
Should I backport [this](https://github.com/JetBrains/resharper-unity/pull/2135/commits/49da3f68b7c7bf9ea5b1f478c9fed67c856126cc) to 212 bugfix?
> mark [UnityTearDown] as [MeansImplicitUseAttribute] via external annotations

- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/MetaTracker.kt
- rider/src/main/resources/META-INF/plugin.xml
Correct MetaTracker for the case with multiple opened Unity/non-Unity solutions
> fix RIDER-70098 - MetaTracker for multiple opened solutions

- CHANGELOG.md
- debugger/ios-list-usb-devices/src/Program.cs
- debugger/usbmuxd/Usbmuxd.cs
- resharper/.idea/.idea.resharper-unity/.idea/runConfigurations/ios_list_usb_devices__net472_.xml
- resharper/.idea/.idea.resharper-unity/.idea/runConfigurations/ios_list_usb_devices__net5_0_.xml
- resharper/resharper-unity.sln.DotSettings
This PR fixes some issues with the helper app that's invoked when the Attach to Unity Process dialog starts. This app loads a native library provided by Unity and polls for Apple devices attached via USB. If the iOS Build Support module isn't installed, the helper app isn't invoked.
Note that the change in location for Unity 2021.2 means that older versions of Rider will be unable to load the library with newer versions of Unity, and USB debugging will not be available. Depending on OS, there might also be a crash dialog shown.
> Fix issues with iOS USB device enumeration app

- resharper/resharper-unity/src/AsmDef/Feature/Services/CodeCompletion/AsmDefDefineConstraintItemsProvider.cs
- resharper/resharper-unity/src/CSharp/Daemon/Stages/BurstCodeAnalysis/Analyzers/ReferenceExpression/BurstStaticReadonlyReadAccessAnalyzer.cs
- resharper/resharper-unity/src/CSharp/Daemon/Stages/BurstCodeAnalysis/Analyzers/ReferenceExpression/BurstWriteAccessAnalyzer.cs
- resharper/resharper-unity/src/CSharp/Daemon/Stages/ContextSystem/CallGraphContext.cs
Related to  #2199
`TestRunner.Abstractions` has copies of NotNull and similar extension methods, but have a fixed version and any usage of its members will raise an error in runtime when the product is updated.
> Drop usages of TestRunner.Abstractions

- resharper/resharper-unity/src/Feature/Caches/DeferredCacheController.cs
- resharper/resharper-unity/src/Yaml/Psi/DeferredCaches/UnityAssetCache.cs
RIDER-71633 will be fixed in 22.1, I guess we should add files and folders to ignore or reuse existing one for code analysis
> Improvment for RIDER-71633, add logging for RIDER-71921

- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/FrontendBackendHost.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/RunConfigurationUtil.kt
> RIDER-70660 Debug Unity test, when we are already attached

- CHANGELOG.md
- resharper/resharper-unity/src/AsmDef/Feature/Services/Daemon/Attributes/AsmDefHighlightingAttributeIds.cs
- rider/gradle.properties
GUID references in a `.asmdef` file show a tooltip with the name of the referenced assembly definition. This `INFO` level highlighter was registered with `TextEffect.TEXT`, but should have been registered with `TextEffect.NONE`.
If registered with `TEXT`, then ReSharper requires non-default values for the highlighter attributes, and throws an exception when trying to use the attribute (e.g. by placing the caret on a GUID reference). If registered with an empty set of attributes, Rider will not pass the details to the front-end and the tooltip is not shown. This change uses `NONE`, so ReSharper ignores the text attributes, and adds one non-default attribute, so that Rider will still pass the highlighter to the frontend (but because it's set to `NONE`, it's ignored.
Resolves part of …
> Fix registration of tooltip only highlighter for ReSharper

- CHANGELOG.md
- resharper/resharper-unity/src/Unity/CSharp/Daemon/Stages/Color/UnityColorHighlighterProcess.cs
- resharper/resharper-unity/test/data/Unity/CSharp/Daemon/Stages/Colors/Color.cs
- resharper/resharper-unity/test/data/Unity/CSharp/Daemon/Stages/Colors/Color.cs.gold
- resharper/resharper-unity/test/data/Unity/CSharp/Daemon/Stages/Colors/Color32.cs
- resharper/resharper-unity/test/data/Unity/CSharp/Daemon/Stages/Colors/Color32.cs.gold
- resharper/resharper-unity/test/src/Unity.Tests/Unity/CSharp/Daemon/Stages/Color/UnityColorHighlightingTest.cs
Show colour preview when creating an instance of `Color` with target typed new.
Fixes [RIDER-64151](https://youtrack.jetbrains.com/issue/RIDER-64151)
> Fix colour highlighting for target typed new

- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorProfileState.kt
because of old serialized value of run configuration param
> fix a case when Attach to UnityEditor sun-configuration doesn't work

- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/LogPanelItem.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelEventRenderer.kt
> fix RIDER-70574 Unity Log does throttle on CPU due to the long log entries

- CHANGELOG.md
- resharper/resharper-unity/src/Unity/Yaml/ProjectModel/MetaProjectFileType.cs
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorer.kt
- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorerFileSystemNode.kt
Fixes [RIDER-67457](https://youtrack.jetbrains.com/issue/RIDER-67457), but I have no idea how to recreate.
> Ensure Unity Explorer project names are distinct

- rider/build.gradle.kts
- rider/buildSrc/build.gradle.kts
- rider/buildSrc/src/main/kotlin/com/jetbrains/rider/plugins/gradle/BackendPaths.kt
- rider/gradle/wrapper/gradle-wrapper.properties
- rider/gradlew
Primarily, this PR updates `gradle-intellij-plugin` to 1.3.1 and removes the workaround for missing execute file permissions in the downloaded SDK on Mac/Linux. Also updates to latest Gradle and the latest plugins.
> Update Gradle and Gradle plugin versions

- CHANGELOG.md
- resharper/resharper-json/src/Json/Psi/JsonNewElementFactory.cs
- resharper/resharper-json/src/Json/Psi/Parsing/JsonNew.psi
- resharper/resharper-json/src/Json/Psi/Parsing/JsonNewParser.cs
- resharper/resharper-json/src/Json/Psi/Tree/IJsonNewArray.cs
- resharper/resharper-json/src/Json/Psi/Tree/IJsonNewObject.cs
- resharper/resharper-json/src/Json/Psi/Tree/Impl/JsonNewArray.cs
- resharper/resharper-json/src/Json/Psi/Tree/Impl/JsonNewObject.cs
- resharper/resharper-unity/src/Unity.Rider/Integration/AsmDef/Feature/Notifications/GeneratedFileNotification.cs
- resharper/resharper-unity/src/Unity.Rider/Integration/Protocol/BackendUnityHost.cs
- resharper/resharper-unity/src/Unity/AsmDef/AsmDefUtils.cs
- resharper/resharper-unity/src/Unity/AsmDef/Feature/Services/Occurrences/AsmDefNameOccurrencePresenter.cs
- resharper/resharper-unity/src/Unity/AsmDef/Feature/Services/QuickFixes/ConvertToGuidReferenceQuickFix.cs
- resharper/resharper-unity/src/Unity/AsmDef/Psi/Caches/AsmDefCache.cs
- resharper/resharper-unity/src/Unity/AsmDef/Psi/Caches/PreProcessingDirectiveCache.cs
- resharper/resharper-unity/src/Unity/AsmDef/Psi/Modules/AsmDefModuleReferenceChangeListener.cs
- resharper/resharper-unity/src/Unity/AsmDef/Psi/Search/GuidReferenceUsageSearchFactory.cs
- resharper/resharper-unity/src/Unity/CSharp/Feature/Services/LiveTemplates/Scope/UnityProjectScopeProvider.cs
- resharper/resharper-unity/src/Unity/Core/ProjectModel/ProjectExtensions.cs
- resharper/resharper-unity/src/Unity/Core/ProjectModel/UnityReferencesTracker.cs
- resharper/resharper-unity/src/Unity/Core/ProjectModel/UnitySolutionTracker.cs
- resharper/resharper-unity/src/Unity/UnityEditorIntegration/Packages/PackageManager.cs
This PR will:
* Automatically update a `.asmdef` file when a reference to another `.asmdef` based project is added or removed. Fixes #852 (and [RIDER-48660](https://youtrack.jetbrains.com/issue/RIDER-48660))
* Remove references from `.asmdef` file if a reference is removed from a `.csproj` file. This means the `.asmdef` file will be updated when e.g. the Remove Unused References refactoring is used. Fixes #1994
* Project references are added as GUID based references, unless existing name based references are being used.
* Asmdef references are correctly handled when modifying or adding/removing `.Player` projects. However, the reference change is not automatically propagated to the Player/non-player project until Unity regenerates the project files.
This PR does not currently handle …
> Update asmdef files when project references are added/removed

- rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/diff/UnityYamlAutomaticExternalMergeTool.kt
Adjust code for the new API from IDEA and fix compilation errors.
Now multiple external merge tools are allowwed in the settings, so we
have to handle this for UnityYamlMerge too.
```
Options for KOTLIN DAEMON:
IncrementalCompilationOptions(super=CompilationOptions(compilerMode=INCREMENTAL_COMPILER,
targetPlatform=JVM, reportCategories=[0], reportSeverity=2,
requestedCompilationResults=[0]kotlinScriptExtensions=[kt, kts, java]),
areFileChangesKnown=false, modifiedFiles=null, deletedFiles=null,
classpathChanges=org.jetbrains.kotlin.incremental.ClasspathChanges$NotAvailable$ClasspathSnapshotIsDisabled@4532cfa5,
workingDir=/opt/buildAgent/work/227d632b77ca8a8e/rider/build/kotlin/compileKotlin,
multiModuleICSettings=MultiModuleICSettings(buildHistoryFile=/opt/buildAgent/work/227d632b77ca8a8e/r …
```
> Fix complilation of UnityYamlMerge tool

- CHANGELOG.md
- resharper/resharper-json/src/Json/Psi/Tree/IJsonNewArray.cs
- resharper/resharper-json/src/Json/Psi/Tree/Impl/JsonNewArray.cs
- resharper/resharper-json/src/Json/Psi/Tree/Impl/JsonNewObject.cs
- resharper/resharper-unity/src/Unity/AsmDef/AsmDefUtils.cs
- resharper/resharper-unity/src/Unity/AsmDef/Feature/Services/ContextActions/ConvertToNamedReferenceContextAction.cs
- resharper/resharper-unity/src/Unity/AsmDef/Feature/Services/Daemon/GuidReferenceInfoAnalyzer.cs
- resharper/resharper-unity/src/Unity/AsmDef/Feature/Services/Daemon/PreferGuidReferenceProblemAnalyzer.cs
- resharper/resharper-unity/src/Unity/AsmDef/Psi/Modules/AsmDefModuleReferenceChangeListener.cs
- resharper/resharper-unity/src/Unity/AsmDef/Psi/Resolve/AsmDefNameReference.cs
- resharper/resharper-unity/src/Unity/AsmDef/Psi/Search/GuidReferenceUsageSearchFactory.cs
- resharper/resharper-unity/src/Unity/CSharp/Daemon/Stages/Analysis/FormerlySerializedAsAttributeProblemAnalyzer.cs
- resharper/resharper-unity/src/Unity/Core/Psi/Modules/UnityExternalFilesPsiModule.cs
- resharper/resharper-unity/src/Unity/Core/Psi/Modules/UnityExternalPsiSourceFileFactory.cs
- resharper/resharper-unity/src/Unity/UnityEditorIntegration/Api/UnityApi.cs
- resharper/resharper-unity/test/data/Unity/AsmDef/Intentions/QuickFixes/ConvertToGuidReference/Test01.asmdef.gold
- resharper/resharper-unity/test/data/Unity/AsmDef/Intentions/QuickFixes/ConvertToGuidReference/TestAsmRef01.asmref.gold
- resharper/resharper-unity/test/data/Unity/AsmDef/Intentions/QuickFixes/ConvertToGuidReference/TestExecuteInScope.asmdef.gold
- resharper/resharper-unity/test/data/Unity/CSharp/Daemon/Stages/Analysis/FormerlySerializedAsAttribute/RedundantFormerlySerializedAs.cs
- resharper/resharper-unity/test/data/Unity/CSharp/Daemon/Stages/Analysis/FormerlySerializedAsAttribute/RedundantFormerlySerializedAs.cs.gold
This PR fixes a couple of issues:
* Stop adding duplicate GUID based references to `.asmdef` files ([RIDER-75001](https://youtrack.jetbrains.com/issue/RIDER-75001))
* Add naive formatting when adding references in `.asmdef` file, by simply copying the leading whitespace of the preceding reference
* Simplify `IsValid` for `UnityExternalPsiSourceFile`. This is called very frequently, and can have a noticeable impact for very large projects
* Fix incorrect redundant `FormerlySerializedAs` attribute warning when applied to the backing field of a property
> Minor fixes

- CHANGELOG.md
- resharper/resharper-unity/src/Unity/AsmDef/Daemon/Errors/AsmDefErrors.xml
- resharper/resharper-unity/src/Unity/AsmDef/Daemon/Errors/RegisterStaticHighlightingsGroups.cs
- resharper/resharper-unity/src/Unity/AsmDef/Feature/Services/Daemon/UnresolvedReferenceHandler.cs
- resharper/resharper-unity/src/Unity/AsmDef/Psi/Modules/AsmDefModuleReferenceChangeListener.cs
- resharper/resharper-unity/test/data/Unity/AsmDef/Daemon/Stages/Resolve/UnresolvedProject/Test01.asmdef.gold
- resharper/resharper-unity/test/data/Unity/AsmDef/Intentions/QuickFixes/ReferencingSelf/Availability/Test01.asmdef.gold
- resharper/resharper-unity/test/src/Unity.Tests/Unity/AsmDef/Feature/Services/Daemon/UnresolvedReferenceHighlightingTests.cs
This PR will disables the automatic removal of references from a `.asmdef` file when the project model changes. For example, unloading a project would be treated the same as deleting a project reference and would remove the reference from the `.asmdef` file. Similarly, if a `.asmdef` file is disabled by editing a define constraint, then the project is regenerated without any references. Rider would interpret that as all references being removed and would delete all references from the `.asmdef` file. Support for updating the `.asmdef` file when a reference is added is still in place. We should reimplement support for removing references in 222.
Secondly, this PR changes the severity of an unknown project reference in a `.asmdef` file. Previously, this was displayed as red code, as an …
> Disable removing references from asmdef files
