JetBrains/resharper-unity

resharper/src/resharper-unity/Help/ShowUnityHelp.cs
=> Navigate to correct documentation page, or search

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/cg/CgCompletionContributor.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/cg/CgFileType.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/cg/CgFileTypeFactory.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/cg/CgIconProvider.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/cg/CgLanguage.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/cg/CgParserDefinition.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/cg/CgSyntaxHighlighter.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/cg/CgSyntaxHighlighterProvider.kt, rider/src/main/resources/META-INF/plugin.xml
Enables keyword highlighting and hippie completion for `.cginc` files on Rider side
=> Rider-side support for pure .cginc files

resharper/src/resharper-unity/Host/Features/SyntaxHighlighting/ShaderLab/ShaderLabSyntaxHighlightingProcess.cs, resharper/src/resharper-unity/Psi/ShaderLab/Parsing/ParserMessages.cs, resharper/src/resharper-unity/Psi/ShaderLab/Parsing/ShaderLab.psi, resharper/src/resharper-unity/Psi/ShaderLab/Parsing/ShaderLabFilteringLexer.cs, resharper/src/resharper-unity/Psi/ShaderLab/Parsing/ShaderLabParser.cs, resharper/src/resharper-unity/Psi/ShaderLab/Parsing/ShaderLabPreProcessor.cs, resharper/src/resharper-unity/Psi/ShaderLab/Parsing/ShaderLabTokenType.Tokens.generated.cs, resharper/src/resharper-unity/Psi/ShaderLab/Parsing/ShaderLabTokenType.Tokens.xml, resharper/src/resharper-unity/Psi/ShaderLab/ShaderLabLanguageService.cs, resharper/test/data/psi/shaderLab/parsing/CgInclude.shader, resharper/test/data/psi/shaderLab/parsing/CgInclude.shader.gold, resharper/test/data/psi/shaderLab/parsing/GlslInclude.shader, resharper/test/data/psi/shaderLab/parsing/GlslInclude.shader.gold, resharper/test/data/psi/shaderLab/parsing/HlslInclude.shader, resharper/test/data/psi/shaderLab/parsing/HlslInclude.shader.gold, resharper/test/data/syntaxHighlighting/shaderLab/SyntaxHighlighting.shader, resharper/test/data/syntaxHighlighting/shaderLab/SyntaxHighlighting.shader.gold, resharper/test/src/Psi/ShaderLab/Parsing/ParserTests.cs, rider/src/main/resources/META-INF/plugin.xml
Fixes #188. Builds upon PR #189
=> Handle CGINCLUDE blocks anywhere in file

Packaging.props, resharper/src/resharper-unity/Psi/ShaderLab/Parsing/ShaderLab.psi, resharper/src/resharper-unity/resharper-unity.rider.nuspec, resharper/src/resharper-unity/resharper-unity.wave08.nuspec, resharper/test/data/psi/shaderLab/parsing/FallbackLodValueErrorNoLiteral.shader, resharper/test/data/psi/shaderLab/parsing/FallbackLodValueErrorNoLiteral.shader.gold, resharper/test/data/psi/shaderLab/parsing/FallbackLodValueErrorWithOff.shader, resharper/test/data/psi/shaderLab/parsing/FallbackLodValueErrorWithOff.shader.gold, resharper/test/data/psi/shaderLab/parsing/FallbackLodValueExpectedLiteral.shader, resharper/test/data/psi/shaderLab/parsing/FallbackLodValueExpectedLiteral.shader.gold, resharper/test/data/psi/shaderLab/parsing/FallbackLodValueProper.shader, resharper/test/data/psi/shaderLab/parsing/FallbackLodValueProper.shader.gold, resharper/test/src/Psi/ShaderLab/Parsing/ParserTests.cs, rider/build.gradle, rider/src/main/resources/META-INF/plugin.xml
Fixes https://youtrack.jetbrains.com/issue/RIDER-8914 by allowing for LOD value to be specified for the Fallback property.
=> Parse fallback with lod value

apiParser/src/ApiParser.csproj, apiParser/src/Program.cs, apiParser/src/TypeResolver.cs, resharper/src/resharper-unity.sln.DotSettings, resharper/src/resharper-unity/Feature/Services/CodeCompletion/UnityEventFunctionRule.cs, resharper/src/resharper-unity/Feature/Services/Generate/GenerateUnityEventFunctionsProvider.cs, resharper/src/resharper-unity/ProjectExtensions.cs, resharper/src/resharper-unity/UnityApi.cs, resharper/src/resharper-unity/UnityType.cs, resharper/src/resharper-unity/UnityVersion.cs, resharper/src/resharper-unity/api.xml, resharper/src/resharper-unity/resharper-unity.rider.nuspec, resharper/src/resharper-unity/resharper-unity.wave09.nuspec, resharper/test/data/codeCompletion/List/MonoBehaviour01.cs.gold, resharper/test/data/generate/InsertMultipleMethods.cs.gold, resharper/test/data/generate/InsertSingleMethod01.cs.gold, resharper/test/data/generate/InsertSingleMethod02.cs.gold, resharper/test/data/generate/ListElements01.cs.gold, resharper/test/data/generate/ListElements08.cs.gold, resharper/test/data/generate/ListElements09.cs.gold, resharper/test/data/generate/ListElements17.cs.gold, resharper/test/data/generate/ListElements18.cs.gold, resharper/test/data/generate/ListElements19.cs.gold, resharper/test/data/generate/MonoBehaviour01.cs.gold, resharper/test/src/Feature/Services/CodeCompletion/UnityEventFunctionCompletionListTest.cs, resharper/test/src/Feature/Services/CodeCompletion/VersionSpecificCompletionListTest.cs, resharper/test/src/Feature/Services/Generate/EventFunctionGeneratorTest.cs, resharper/test/src/TestUnityAttribute.cs, rider/src/main/resources/META-INF/plugin.xml
Fixes several issues:
* Code completion and method generation broken with newer versions of Unity (#219)
* Update Unity API up to 2017.30.0b3 (#218)
* Recognise projects referencing modularised UnityEngine assemblies as Unity projects (#241)
=> Unity API version updates

resharper/src/resharper-unity/Unity3dRider/Assets/Plugins/Editor/JetBrains/RiderAssetPostprocessor.cs
https://github.com/JetBrains/resharper-unity/issues/270
=> fix for generating custom assembly references from mcs.rsp

resharper/src/resharper-unity/Unity3dRider/Assets/Plugins/Editor/JetBrains/RiderAssetPostprocessor.cs
a good thing for teams where some want to use VSTU - the flavour will activate the extra functionality in VS
=> update project guids to Unity-project-guid

resharper/Directory.Build.props, resharper/src/resharper-unity/ShaderLab/Daemon/Stages/ShaderLabErrorStage.cs, resharper/src/resharper-unity/resharper-unity.resharper.csproj, resharper/test/src/tests.resharper.csproj
=> SDK change fix

.gitignore, apiParser/.idea/.idea.apiParser/.idea/indexLayout.xml, apiParser/.idea/.idea.apiParser/.idea/vcs.xml, apiParser/src/ApiNode.cs, apiParser/src/ApiParser.cs, apiParser/src/ApiParser.csproj, apiParser/src/ApiType.cs, apiParser/src/Program.cs, apiParser/src/TypeResolver.cs, apiParser/src/UnityApi.cs, resharper/src/resharper-unity/ApiXml.cs, resharper/src/resharper-unity/api.xml
Also includes some more undocumented APIs.
Fixes #365, fixes #394. See also RIDER-12649
=> Update API to Unity 2018.1

.gitignore, resharper/src/resharper-unity/Rider/UnityEditorProtocol.cs, resharper/src/resharper-unity/Rider/UnityRefreshTracker.cs
RIDER-14270 Component JetBrains.ReSharper.Plugins.Unity.Rider.UnityRefresher
=> fix null ref

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/actions/RefreshInUnityAction.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/actions/UnityActions.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelToolbarBuilder.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelView.kt, rider/src/main/resources/META-INF/plugin.xml
https://github.com/JetBrains/resharper-unity/issues/377
=> Unity actions shortcuts (Play/Pause/Refresh)

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/actions/RefreshInUnityAction.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/actions/UnityActions.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/actions/UnityPluginShowSettingsAction.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/UnityToolWindowManager.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelToolbarBuilder.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelView.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ui/UnityImportantActions.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ui/UnityStatusBarIcon.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ui/UnityUIManager.kt, rider/src/main/resources/META-INF/plugin.xml
=> implement RIDER-13438

unity/JetBrains.Rider.Unity.Editor/EditorPlugin/OnOpenAssetHandler.cs
minor refactoring to provide API for other plugins.
=> https://github.com/JetBrains/resharper-unity/issues/475

resharper/src/resharper-unity/Feature/Services/CodeCompletion/UnityEventFunctionRule.cs
See #421, [RIDER-14127](https://youtrack.jetbrains.com/issue/RIDER-14127), [RIDER-14389](https://youtrack.jetbrains.com/issue/RIDER-14389)
=> Fixes a couple of exceptions

resharper/src/resharper-unity/Rider/UnityEditorProtocol.cs, resharper/src/resharper-unity/Rider/UnityModel.Generated.cs, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/UnityModel.Generated.kt, unity/JetBrains.Rider.Unity.Editor/EditorPlugin/NonUnity/UnityModel.Generated.cs, unity/JetBrains.Rider.Unity.Editor/EditorPlugin/PluginEntryPoint.cs, unity/JetBrains.Rider.Unity.Editor/EditorPlugin/UnityEventLogSender.cs
=> Protocol connection for LogModelInitialized sometimes brakes on Protocol Reconnect.

resharper/src/resharper-unity/Feature/Services/LiveTemplates/UnityProjectScopeProvider.cs, resharper/src/resharper-unity/ProjectExtensions.cs, resharper/src/resharper-unity/ProjectModel/MetaFileTracker.cs, resharper/src/resharper-unity/ProjectModel/UnityReferencesTracker.cs, resharper/src/resharper-unity/Rider/UnityPluginDetector.cs
=> File Templates

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/DefaultRunConfigurationGenerator.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityDebugConfigurationType.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ui/UnityImportantActions.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ui/UnityStatusBarIcon.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ui/UnityUIManager.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/UnityIcons.kt
Two changes:
1. Writes minimised UI flag to `workspaces.xml`. Death to `other.xml`!
2. Updates the wording on the connected icon in the status bar
=> Minor frontend tweaks

resharper/src/resharper-unity/Rider/UnityEditorProtocol.cs, resharper/src/resharper-unity/Rider/UnityOptionsPage.cs, resharper/src/resharper-unity/Rider/UnityRefreshTracker.cs, resharper/src/resharper-unity/Settings/UnitySettings.cs
Disable refreshing when ctrl-s is pressed without disabling auto-refresh in Unity
=> #478 Setting to disable AutoRefresh

unity/JetBrains.Rider.Unity.Editor/EditorPlugin/AssetPostprocessors/CsprojAssetPostprocessor.cs, unity/JetBrains.Rider.Unity.Editor/EditorPlugin/PluginSettings.cs
Is fixing https://github.com/JetBrains/resharper-unity/issues/528
=> Add setting to override LangVersion

resharper/src/resharper-unity/Rider/UnityPluginDetector.cs, unity/JetBrains.Rider.Unity.Editor/EditorPlugin/PluginEntryPoint.cs, unity/JetBrains.Rider.Unity.Editor/EditorPlugin/RiderLogger.cs, unity/JetBrains.Rider.Unity.Editor/EditorPlugin/Utils/RiderScriptableSingleton.cs, unity/JetBrains.Rider.Unity.Editor/EditorPlugin/Utils/ScriptObjectSingleton.cs
https://github.com/JetBrains/resharper-unity/issues/527
=> Speedup play #527

resharper/src/resharper-unity/ProjectExtensions.cs, resharper/src/resharper-unity/Rider/UnityEditorProtocol.cs, rider/src/main/kotlin/com/jetbrains/rider/UnityReferenceDiscoverer.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/actions/UnityActions.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ui/UnityUIManager.kt, unity/EditorPlugin/ModelWithLifetime.cs, unity/EditorPlugin/NonUnity/RiderProtocolController.cs, unity/EditorPlugin/OnOpenAssetHandler.cs, unity/EditorPlugin/PluginEntryPoint.cs, unity/EditorPlugin/PluginSettings.cs, unity/EditorPlugin/UnityEventLogSender.cs
https://github.com/JetBrains/resharper-unity/issues/581
=> Protocol connection to every solution opened from root folder

apiParser/src/ApiNode.cs, apiParser/src/ApiParser.cs, apiParser/src/ApiType.cs, apiParser/src/Program.cs, apiParser/src/TypeResolver.cs, apiParser/src/UnityApi.cs, resharper/src/resharper-unity/api.xml, resharper/test/data/daemon/IdentifierTooltip/EventFunction01.gold, resharper/test/data/daemon/Stages/Analysis/UnityEventFunctionAnalyzer.cs.gold, resharper/test/data/daemon/Stages/GutterMark/Test01.cs.gold
=> Update API to 2018.2 (beta)

unity/EditorPlugin/PluginEntryPoint.cs, unity/EditorPlugin/PluginSettings.cs
Discussed in https://github.com/JetBrains/resharper-unity/pull/609
=> Pr 609 Implemented assembly locking during play

resharper/src/resharper-unity/Json/Feature/Services/Daemon/AsmDefReferencingSelfProblemAnalyzer.cs
Fixes [RIDER-17702](https://youtrack.jetbrains.com/issue/RIDER-17702)
=> Fix null reference exception in .asmdef analysis

unity/EditorPlugin/AssetPostprocessors/CsprojAssetPostprocessor.cs
Version check was accidentally removed
=> Stop unnecessary writes to disk for .csproj

resharper/src/resharper-unity/UnityApi.cs, resharper/src/resharper-unity/UnityType.cs
Fixes [RIDER-18407](https://youtrack.jetbrains.com/issue/RIDER-18407)
=> Fix assertion for incorrect context

resharper/src/resharper-unity/Rider/UnitTesting/UnityNUnitServiceProvider.cs
=> first run from gutter mark should try to run in Unity by default. 

apiParser/src/Program.cs, resharper/src/resharper-unity/api.xml, unity/EditorPlugin/AssetPostprocessors/CsprojAssetPostprocessor.cs, unity/EditorPlugin/AssetPostprocessors/SlnAssetPostprocessor.cs
=> Fix Unity version corresponding to OnGeneratedCSProject

resharper/src/resharper-unity/Rider/UnityRiderUnitTestCoverageAvailabilityChecker.cs
* removes `Cover` option from gutter mark
* disable `Cover` button for test elements
Checked manually by downloading installer corresponding the SDK and installing plugin here.
=> #RIDER-17815 Fixed

unity/EditorPlugin/MainThreadDispatcher.cs
is expected to fix exception "UnityException: get_isPlaying can only be called from the main thread."
https://jetbrains.slack.com/archives/G4EUFJYDB/p1533934225000391
=> fix MainThreadDispatcher ourUIThread

unity/EditorPlugin/AssetPostprocessors/CsprojAssetPostprocessor.cs
I clearly made a complete mess of checking for versions with response files. Following on from #729, there's a version check in `SetManuallyDefinedCompilerSettings` that checks for 2017.1 and later and short circuits any further processing.
This is fine for the `unsafe` or C# defines check, as these are handled directly by Unity 2017.1+, but it also skips the check for adding references from the response files. This PR removes that initial check.
=> Fix adding references from response files

rider/src/main/kotlin/com/jetbrains/rider/UnityReferenceDiscoverer.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/RiderUnityHost.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/SaveAllTracker.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/PackagesManager.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorer.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorerNode.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/UnityToolWindowFactory.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/UnityToolWindowManager.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelEventList.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ui/UnityUIManager.kt, rider/src/main/kotlin/com/jetbrains/rider/settings/RiderUnitySettings.kt
I am worried about removing 
override fun getData(dataId: String): Any? {
=> fix compile kotlin

unity/EditorPlugin/PluginEntryPoint.cs
=> fix reentrancy for model.Pause

resharper/src/resharper-unity/Rider/UnityRiderUnitTestCoverageAvailabilityChecker.cs
https://youtrack.jetbrains.com/issue/RIDER-18961
=> Dotcover availability with Standalone Nunit launcher

resharper/src/resharper-unity/ShaderLab/Psi/Parsing/ShaderLab.psi, resharper/test/data/ShaderLab/Psi/Parsing/Blending.shader, resharper/test/data/ShaderLab/Psi/Parsing/Blending.shader.gold
=> Fix bug in ShaderLab parsing

rider/frontend.gradle, rider/src/main/kotlin/com/jetbrains/rider/UnityConfigurationImpl.kt, rider/src/main/kotlin/com/jetbrains/rider/UnityReferenceDiscoverer.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/RiderUnityHost.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/javascript/UnityPackageJsonNotifierConfiguration.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ui/UnityUIManager.kt, rider/src/main/resources/META-INF/PluginAppenderPluginPart.xml, rider/src/main/resources/META-INF/plugin.xml
=> Suppress prompt to run npm install

resharper/src/resharper-unity.sln.DotSettings, resharper/src/resharper-unity/ProjectExtensions.cs, resharper/src/resharper-unity/ProjectModel/UnitySolutionTracker.cs, resharper/src/resharper-unity/Rider/UnityEditorProtocol.cs, resharper/src/resharper-unity/Rider/UnityPluginInstaller.cs, resharper/src/resharper-unity/Rider/UnityRiderUnitTestCoverageAvailabilityChecker.cs, resharper/src/resharper-unity/Rider/UnitySolutionTracker.cs
refer to https://github.com/JetBrains/resharper-unity/blob/183/resharper/src/resharper-unity/ProjectModel/UnitySolutionTracker.cs
https://github.com/JetBrains/resharper-unity/issues/581
=> Avoid waiting for full solution opening for installing Editor Plugin

unity/EditorPlugin/PluginSettings.cs
=> Added version info to preferences

resharper/src/resharper-unity/CSharp/Psi/Resolve/UnityEventFunctionReference.cs, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelView.kt
Fixes [RIDER-18699](https://youtrack.jetbrains.com/issue/RIDER-18699)
=> Fix exception when resolving after type rename

resharper/src/resharper-unity/Rider/TempAnnotationsLoader.cs, resharper/src/resharper-unity/Rider/UnityEditorProtocol.cs, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorProfileState.kt
Revert "Remove obsolete workaround"
This reverts commit a2f62aa5a9d652dcfd831f6fd6934c151f924e29.
=> Restore Annotations workaround and Restore Protocol reconnect by FileSystemWatcher

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelEventList.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelView.kt
Set similar font as configured for the editor
=> Set font for Unity Log View, fix #824

unity/EditorPlugin/PluginEntryPoint.cs
https://github.com/JetBrains/resharper-unity/issues/846
=> call RequestScriptReload on force Refresh

resharper/src/resharper-unity/CSharp/Daemon/Stages/PerformanceCriticalCodeAnalysis/PerformanceCriticalCodeAnalysisStage.cs
Fix NPE and repeated message in tooltip
=> fixes in performance stage

resharper/resharper-unity/src/CSharp/Daemon/Stages/Analysis/ComponentPropertyAccessProblemAnalyzer.cs, resharper/resharper-unity/src/CSharp/Psi/Resolve/ExpectedObjectTypeFilter.cs, resharper/resharper-unity/src/DeclaredElementExtensions.cs
Fix filter for builtin component
=> [Fix] Repeated builtin component property access inspection

resharper/resharper-unity/src/Rider/UnityEditorProtocol.cs, resharper/resharper-unity/src/Rider/UnityRefreshTracker.cs
https://github.com/JetBrains/resharper-unity/issues/866
=> fix calling refresh without checking corresponding setting value

unity/EditorPlugin/PluginEntryPoint.cs
https://github.com/JetBrains/resharper-unity/pull/874#issuecomment-435509421
=> revert PR#874. It was causing crashes on Windows 

resharper/resharper-unity/src/ProjectModel/Caches/UnityProjectFileCacheProvider.cs, unity/EditorPlugin/PluginEntryPoint.cs
https://github.com/JetBrains/resharper-unity/pull/874#issuecomment-435519012
++ fix RIDER-21237
=> SyncSolution once on each Unity startup

apiParser/src/ApiParser.cs, apiParser/src/UnityApi.cs, resharper/resharper-unity/src/api.xml, resharper/resharper-unity/test/data/CSharp/Daemon/IdentifierTooltip/EventFunction01.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/GutterMark/Test01.cs.gold
=> Update API information to 2018.3.0b9

resharper/resharper-unity/src/Rider/UnitTesting/RunViaUnityEditorStrategy.cs, resharper/resharper-unity/src/Rider/UnityPluginInstaller.cs
1. Exception on Cancel tests
2. Installing plugin on changing setting when project is opened as a folder.
=> Minor fixes

resharper/resharper-unity/src/Rider/UnityPluginInstaller.cs
This would refresh Unity in case when there were some editor plugin and we updated it.
Part of https://github.com/JetBrains/resharper-unity/issues/581
=> Call Unity refresh after plugin install

resharper/resharper-unity/src/Rider/UnityInstallationSynchronizer.cs, resharper/resharper-unity/src/UnityVersion.cs, resharper/resharper-unity/test/src/CSharp/UnityVersionTest.cs, rider/protocol/src/main/kotlin/model/rider/RdUnityModel.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/actions/StartUnityAction.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/UnityInstallationFinder.kt
…etBrains.ReSharper.Plugins.Unity.UnityApi. Exception has been thrown by the target of an invocation. Could not find any recognizable digits.
=> fix RIDER-22276 + Show Unity version in Start Unity action

resharper/resharper-unity/src/CSharp/Daemon/Stages/PerformanceCriticalCodeAnalysis/PerformanceCriticalCodeHighlightings.cs, resharper/resharper-unity/src/CSharp/Feature/Services/Explanatory/UnityCodeInspectionWikiDataProvider.cs, resharper/resharper-unity/src/Rider/CodeInsights/RiderUnityImplicitUsageHighlightingContributor.cs, resharper/resharper-unity/src/Rider/FindUsageRequestExtension.cs, resharper/resharper-unity/src/Rider/UnityEditorFindUsageResultCreator.cs, resharper/resharper-unity/src/Rider/UnityEditorOccurrence.cs, resharper/resharper-unity/src/Rider/UnityEditorProtocol.cs, resharper/resharper-unity/src/UnityFocusUtil.cs, rider/protocol/src/main/kotlin/model/editorPlugin/EditorPluginModel.kt, rider/protocol/src/main/kotlin/model/rider/RdUnityModel.kt, unity/EditorPlugin/Navigation/EntryPoint.cs, unity/EditorPlugin/Navigation/ShowUtil.cs, unity/EditorPlugin/Navigation/Window/AbstractUsageElement.cs, unity/EditorPlugin/Navigation/Window/FindUsagesWindow.cs, unity/EditorPlugin/Navigation/Window/FindUsagesWindowTreeState.cs
1. Add target for Find usages window
2. Add "Why Rider suggest it for each new inspection"
3. Fix bug with navigation after domain reload
=> Docs, ux & bug fixes

resharper/resharper-unity/src/Rider/UnityEditorProtocol.cs, rider/protocol/src/main/kotlin/model/rider/RdUnityModel.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/notifications/OutOfSyncEditorNotification.kt, rider/src/main/resources/META-INF/plugin.xml
Fix for https://github.com/JetBrains/resharper-unity/issues/581
=> Handle outdated protocol and the automatic update is unchecked.

unity/EditorPlugin/OnOpenAssetHandler.cs
https://github.com/JetBrains/resharper-unity/issues/981
=> Support Scripted Importers

CHANGELOG.md, resharper/resharper-unity/src/CSharp/Daemon/Errors/CSharpErrors.xml, resharper/resharper-unity/src/CSharp/Feature/Services/Daemon/UnityObjectReferenceErrorHandler.cs, resharper/resharper-unity/src/CSharp/Psi/Resolve/UnityObjectTypeOrNamespaceReference.cs, resharper/resharper-unity/src/CSharp/Psi/Resolve/UnityResolveErrorType.cs, resharper/resharper-unity/src/resharper-unity.resharper.nuspec, resharper/resharper-unity/test/data/CSharp/Resolve/UnityObjectTypeInStringLiteral/AddComponent01.cs.gold, resharper/resharper-unity/test/data/CSharp/Resolve/UnityObjectTypeInStringLiteral/GetComponent01.cs.gold, resharper/resharper-unity/test/data/CSharp/Resolve/UnityObjectTypeInStringLiteral/ScriptableObjectCreateInstance01.cs.gold, rider/src/main/resources/META-INF/plugin.xml
For string literal use in GetComponent, AddComponent and ScriptableObject.CreateInstance
Fixes RIDER-23429
=> Downgrade unresolved symbol error to warning

resharper/resharper-unity/src/Rider/UnityOptionsPage.cs, resharper/resharper-unity/src/Rider/UnityRefreshTracker.cs, resharper/resharper-unity/src/Yaml/Psi/Modules/UnityExternalFilesPsiModule.cs, resharper/resharper-unity/test/src/CSharp/Daemon/UsageChecking/UsageCheckBaseTest.cs, resharper/resharper-yaml/src/Psi/Parsing/YamlParser.cs
=> Fix API changes

resharper/resharper-unity/src/Rider/UnityPathTemplateParameter.cs
=> UnityClassLib project creation when Unity installation was not found

resharper/resharper-unity.sln.DotSettings, unity/EditorPlugin/AssetPostprocessors/CsprojAssetPostprocessor.cs, unity/EditorPlugin/PluginEntryPoint.cs, unity/EditorPlugin/UnityUtils.cs
Unique names for log files for the case of multiple Unity instances
GetApiCompatibilityLevel fails in batch mode
Some Rename Refactoring
=> Unique names for log files

unity/EditorPlugin/RiderPathLocator.cs
1. Fix for Mac https://youtrack.jetbrains.com/issue/RIDER-24173
2. Use history.json to select only actual build in toolbox
=> Fix RiderPathLocator

resharper/resharper-unity/src/CSharp/Daemon/Stages/PerformanceCriticalCodeAnalysis/ExpensiveCodeCallGraphAnalyzer.cs, resharper/resharper-unity/src/CSharp/Daemon/Stages/PerformanceCriticalCodeAnalysis/PerformanceCriticalCodeAnalysisStage.cs, resharper/resharper-unity/src/CSharp/Daemon/Stages/PerformanceCriticalCodeAnalysis/PerformanceCriticalCodeCallGraphAnalyzer.cs, resharper/resharper-unity/src/CSharp/Daemon/Stages/PerformanceCriticalCodeAnalysis/PerformanceCriticalCodeStageUtil.cs, resharper/resharper-unity/src/CSharp/Daemon/Stages/PerformanceCriticalCodeAnalysis/StringBasedInvocationEdgeChecker.cs, resharper/resharper-unity/src/CSharp/Daemon/Stages/PerformanceCriticalCodeAnalysis/UnityCallGraphSuppressor.cs, resharper/resharper-unity/src/CSharp/Daemon/Stages/PerformanceCriticalCodeAnalysis/VisualStudio/VSPerformanceCriticalCodeAnalysisStage.cs, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/resharper/UnityEventFunctionAnalyzer.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/rider/UnityEventFunctionAnalyzer.cs.gold, resharper/resharper-unity/test/src/CSharp/Daemon/Stages/Analysis/CSharpHighlightingTestBase.cs, resharper/resharper-unity/test/src/CSharp/Daemon/Stages/Analysis/UnityEventFunctionAnalyzerTests.cs, resharper/resharper-unity/test/src/CSharp/Daemon/Stages/PerformanceCriticalCodeAnalysis/PerformanceCriticalCodeStageTestBase.cs, resharper/resharper-unity/test/src/CSharp/Daemon/Stages/PerformanceCriticalCodeAnalysis/PerformanceStageTests.cs, resharper/resharper-unity/test/src/CSharp/Daemon/Stages/PerformanceCriticalCodeAnalysis/UnityTestCallGraphSuppressor.cs, resharper/resharper-unity/test/src/CSharp/Intentions/QuickFixes/CSharpQuickFixAfterSwaTestBase.cs, resharper/resharper-unity/test/src/CSharp/Intentions/QuickFixes/MoveCameraMainQuickFixTests.cs, resharper/resharper-unity/test/src/CSharp/Intentions/QuickFixes/MoveCostlyMethodQuickFixTests.cs, resharper/resharper-unity/test/src/CSharp/Intentions/QuickFixes/MoveNullComparisonQuickFixTests.cs
This PR adds cross-file performance critical code analysis
=> Move performance critical code analysis to call graph, update tests

resharper/resharper-unity/src/Rider/UnityEditorProtocol.cs, unity/EditorPlugin/OnOpenAssetHandler.cs, unity/EditorPlugin/PluginEntryPoint.cs
Refactoring regarding https://github.com/JetBrains/resharper-unity/issues/888
=> Refactoring to support OnOpenedAsset(int instanceID, int line, int column)

apiParser/src/Program.cs, resharper/resharper-unity/src/api.xml
API details updated to the latest 2019.1.0b4. Currently no changes for 2019.2.0a4. Will update again later in the Rider 2019.1 release cycle.
=> Update API to 2019.1.0b4

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelEventList.kt, unity/EditorPlugin/AssetPostprocessors/CsprojAssetPostprocessor.cs
fix https://github.com/JetBrains/resharper-unity/issues/367
=> navigation to editor from logview

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/VcsPullTracker.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelEventList.kt, rider/src/main/resources/META-INF/plugin.xml
=> Automatically call Unity refresh on vcs pull 

resharper/resharper-unity/src/Help/ShowUnityHelp.cs, resharper/resharper-unity/src/Rider/UnitTesting/RunViaUnityEditorStrategy.cs, resharper/resharper-unity/src/Rider/UnityInstallationSynchronizer.cs, resharper/resharper-unity/src/Rider/UnityMonoPathProvider.cs, resharper/resharper-unity/src/UnityInstallationFinder.cs
fix https://github.com/JetBrains/resharper-unity/issues/1104
=> Pass Unity version to frontend even for a Dll project

resharper/resharper-unity/src/Yaml/Rider/Host/Feature/UnityYamlExtraGroupingRulesProvider.cs
Fixes [RIDER-26119](https://youtrack.jetbrains.com/issue/RIDER-26119)
=> Fix exception by providing compilation context

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorRunConfiguration.kt
=> Update texts in run configurations

resharper/resharper-unity/src/Rider/UnityEditorProtocol.cs
https://github.com/JetBrains/resharper-unity/issues/1163
=> Fix protocol connection on linux

resharper/resharper-unity/src/Yaml/Psi/Modules/UnityExternalFilesModuleProcessor.cs, resharper/resharper-unity/src/Yaml/Psi/Resolve/UnityEventTargetReference.cs, resharper/resharper-unity/src/Yaml/Psi/Search/UnityYamlSearchGuru.cs
1. Fix errors in scene files for virtual/abstract/override methods fr event handlers
2. Correctly find usages for virtual methods
3. Fix usage counter when yaml file was opened in Rider
=> Resolve fixes for yaml files, usage counter & find usages fixes for event handlers

CHANGELOG.md, resharper/resharper-unity/src/Rider/UnityPluginInstaller.cs, rider/src/main/resources/META-INF/plugin.xml, unity/EditorPlugin/PluginEntryPoint.cs
Merge only after com.unity.ide.rider with corresponding changes lands
=> Avoid coping EditorPlugin for Unity 2019.2+

resharper/resharper-unity/src/UnityApi.cs, resharper/resharper-unity/src/Yaml/Psi/Resolve/EventHandlerSymbolFilter.cs, resharper/resharper-unity/src/Yaml/Psi/Resolve/UnityEventTargetReference.cs, resharper/resharper-unity/src/Yaml/Psi/Resolve/UnityEventTargetReferenceFactory.cs, resharper/resharper-unity/src/Yaml/Psi/Search/UnityYamlSearchGuru.cs, resharper/resharper-unity/src/Yaml/Psi/Search/UnityYamlUsageSearchFactory.cs
Fix RIDER-27445
Fix RIDER-27684
=> Fix errors in event handlers resolve

resharper/resharper-unity/src/Application/UI/Options/VisualStudio/ReSharperOptionsPage.cs, resharper/resharper-unity/src/Rider/UnityOptionsPage.cs, resharper/resharper-unity/src/Yaml/Psi/Modules/UnityExternalFilesModuleProcessor.cs
Fix RIDER-27918
Fix RIDER-27907
=> Do not add yaml files to swea if unity yaml parsing is disabled

resharper/resharper-unity/test/src/CSharp/Intentions/QuickFixes/CSharpQuickFixAfterSwaTestBase.cs, rider/backend.gradle, rider/frontend.gradle
=> Fix tests in CI (hopefully)

rider/.idea/gradle.xml, rider/frontend.gradle
Add experimental unsigned types option to Gradle scripts, to allow usage of experimental features in Rd generated code.
=> Fix frontend compilation

resharper/resharper-unity/src/CSharp/Daemon/Stages/Highlightings/IconsProviders/InitialiseOnLoadCctorDetector.cs, resharper/resharper-unity/src/CSharp/Daemon/Stages/Highlightings/IconsProviders/TypeDetector.cs, resharper/resharper-unity/src/CSharp/Daemon/Stages/Highlightings/IconsProviders/UnityCommonIconProvider.cs, resharper/resharper-unity/src/CSharp/Daemon/Stages/Highlightings/UnityHighlightingAbstractStage.cs, resharper/resharper-unity/src/KnownTypes.cs, resharper/resharper-unity/src/Rider/CodeInsights/UnityCodeInsightFieldUsageProvider.cs, resharper/resharper-unity/src/Rider/Highlightings/IconsProviders/RiderTypeDetector.cs, resharper/resharper-unity/src/Rider/Highlightings/IconsProviders/RiderUnityCommonIconProvider.cs, resharper/resharper-unity/src/Yaml/Psi/Caches/UnityEditorPropertyValues/PropertyValueLocalCache.cs, resharper/resharper-unity/src/Yaml/Psi/Caches/UnityEditorPropertyValues/UnityGameObjectNamesCache.cs, resharper/resharper-unity/src/Yaml/Psi/Caches/UnityEditorPropertyValues/UnityPropertyValueCache.cs, resharper/resharper-unity/src/Yaml/Psi/Parsing/IUnityYamlFile.cs, resharper/resharper-unity/src/Yaml/Psi/Parsing/UnityYamlFile.cs, resharper/resharper-unity/src/Yaml/Psi/Parsing/UnityYamlParser.cs, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/FormerlySerializedAsAttribute/rider/NonUnityFields.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/FormerlySerializedAsAttribute/rider/RedundantFormerlySerializedAs.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/RedundantAttributeOnTarget/rider/HideInInspector.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/resharper/InstantiateScriptableObjectWarning.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/resharper/UnityEventFunctionAnalyzer.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/rider/DrawGizmoAttributeProblemAnalyzer.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/rider/HiddenEventFunctions.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/rider/InstantiateMonoBehaviourWarning.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/rider/RedundantHideInInspectorAttribute.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/rider/RedundantSerializeFieldAttribute.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/rider/UnityEventFunctionAnalyzer.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/GutterMark/rider/Test01.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/UnityHighlightingsStage/rider/CommonTest01.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/UnityHighlightingsStage/rider/CommonTest02.cs.gold
1. Better enum presentation
2. Better bool presentation
3. Do not show code vision for not presentable types
4. Show changes for scene, not for values
=> Improve presentation for properties code vision

resharper/.idea/.idea.rider-unity/.idea/runConfigurations/runIde__offline_.xml, resharper/resharper-unity/src/Rider/UnityRefreshTracker.cs
fix https://github.com/JetBrains/resharper-unity/issues/1253
=> Fix double Refresh

resharper/resharper-unity/src/CSharp/Feature/Services/ContextActions/GenerateUnityEventFunctionsAction.cs, resharper/resharper-unity/src/Rider/CodeInsights/UnityUsagesCodeVisionProvider.cs, resharper/resharper-unity/src/Rider/Highlightings/IconsProviders/RiderTypeDetector.cs, resharper/resharper-unity/src/Yaml/Psi/Caches/UnityEditorPropertyValues/YamlTrigramIndexBuilder.cs, resharper/resharper-unity/src/Yaml/Psi/Modules/UnityExternalFilesPsiModule.cs, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/resharper/HiddenEventFunctions.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/rider/HiddenEventFunctions.cs.gold
1. Update gold
2. Fix RIDER-29771
3. Fix RIDER-30186
=> Trigram index performance & fixes

resharper/resharper-unity/src/Rider/CodeInsights/UnityCodeInsightFieldUsageProvider.cs
Show notification after clicking property code vision if Unity Editor is not running
=> Add tooltip for property code vision

CHANGELOG.md, resharper/resharper-unity/src/annotations/UnityEngine.PhysicsModule.xml, resharper/resharper-unity/src/annotations/UnityEngine.xml, resharper/resharper-unity/src/resharper-unity.resharper.nuspec, resharper/resharper-unity/test/data/CSharp/Psi/CodeAnnotations/CharacterControllerCollisionFlagsAnnotation.cs, resharper/resharper-unity/test/data/CSharp/Psi/CodeAnnotations/CharacterControllerCollisionFlagsAnnotation.cs.gold, resharper/resharper-unity/test/src/CSharp/Psi/CodeAnnotations/FixCharacterControllerCollisionFlagAnnotationTests.cs, rider/src/main/resources/META-INF/plugin.xml
Fixes [RIDER-28661](https://youtrack.jetbrains.com/issue/RIDER-28661).
=> Add external [Flags] annotation for CollisionFlags

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ui/UnitTest/SwitchUnitTestLauncherComboBoxAction.kt
https://youtrack.jetbrains.com/issue/RIDER-19513
=> enable play mode tests in UI

resharper/resharper-unity/src/Rider/UnityEditorProtocol.cs, rider/protocol/src/main/kotlin/model/editorPlugin/EditorPluginModel.kt, rider/protocol/src/main/kotlin/model/rider/RdUnityModel.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelModel.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelView.kt, unity/EditorPlugin/PluginEntryPoint.cs
https://github.com/JetBrains/resharper-unity/issues/1281
=> clear logs on play

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorer.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorerProjectModelViewUpdater.kt
Fixes [DEXP-482252](https://youtrack.jetbrains.com/issue/DEXP-482252)
=> Fix exception when opening project with hidden Unity Explorer

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorProfileState.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorRunConfiguration.kt
=> Verify existence of appropriate Unity Editor asynchronously during creation of worker cmd

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/actions/UnityPluginShowSettingsAction.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelToolbarBuilder.kt
https://jetbrains.slack.com/archives/GH9S2GGRG/p1569957612013600
=> fix Icon and Hint for ShowSettings action in UnityLogView toolbar

resharper/resharper-unity/src/Rider/ConnectionTracker.cs
This reverts commit fd85811796e722f3bfce6555645cf0f40cdd9be8.
=> Revert "avoid using locks.QueueRecurring (#1317)"

resharper/resharper-unity/src/ProjectExtensions.cs, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelView.kt
fix https://github.com/JetBrains/resharper-unity/issues/1393
=> Fix logview scroll

unity/EditorPlugin/OnOpenAssetHandler.cs, unity/EditorPlugin/RiderPathProvider.cs
=> Avoid starting Rider, which is not selected as ExternalEditor

resharper/resharper-unity/src/Rider/UnitTesting/RunViaUnityEditorStrategy.cs, resharper/resharper-unity/src/Rider/UnitTesting/UnityRiderUnitTestCoverageAvailabilityChecker.cs, unity/EditorPlugin/AfterUnity56/UnitTesting/UnityEditorTestLauncher.cs
remove hack for cancelling tests
move file to corresponding place
add a call to new cancelling tests api
=> fix RIDER-35494 and other fixes

resharper/resharper-unity/src/Rider/Packages/ManifestJson.cs, resharper/resharper-unity/src/Rider/Packages/PackageValidator.cs, resharper/resharper-unity/src/Rider/UnitTesting/RunViaUnityEditorStrategy.cs, resharper/resharper-unity/src/Rider/UnityPluginInstaller.cs
=> Error messages, when testrun fails

rider/build.gradle, rider/buildSrc/src/main/kotlin/com/jetbrains/rider/plugins/gradle/BackendPaths.kt, rider/gradlew, rider/gradlew.bat
- Add jvm wrapper plugin to use JDK 11 in builds.
- Fix some bugs in build scripts.
=> Fix some build issues.

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ContentModelUpdater.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/SaveAllTracker.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/VcsPullTracker.kt, rider/src/main/resources/META-INF/plugin.xml
fix https://github.com/JetBrains/resharper-unity/issues/698
=> Refactor frontend component registration

resharper/resharper-unity/src/ProjectExtensions.cs, resharper/resharper-unity/src/ProjectModel/MetaFileTracker.cs
* fix https://github.com/JetBrains/resharper-unity/issues/1481
=> Avoid creating meta files outside Assets and Packages (#1489)

resharper/resharper-unity/src/Rider/UnityEditorProtocol.cs, rider/build.gradle
1) bump rdgen version
2) Wire should not have several protocols, 1 to 1 mapping
=> Update rdgen & fix exception in protocol

resharper/resharper-unity/src/Rider/UnityEditorProtocol.cs, resharper/resharper-unity/src/Rider/UnityInstallationSynchronizer.cs, resharper/resharper-unity/src/Rider/UnityPluginInstaller.cs, resharper/resharper-unity/src/UnityVersion.cs, rider/protocol/src/main/kotlin/model/rider/RdUnityModel.kt, rider/src/main/kotlin/com/jetbrains/rider/UnityProjectDiscoverer.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/notifications/OpenUnityProjectAsFolderNotification.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/packageManager/PackageManager.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/UnityInstallationFinder.kt
Helps with https://github.cds.internal.unity3d.com/unity/com.unity.ide.rider/issues/64
from Rider side.
=> Different notification text, when Rider package is missing

CHANGELOG.md, rider/build.gradle, rider/buildSrc/build.gradle.kts, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/quickDoc/QuickJavaDocActionCustomization.kt, rider/src/main/resources/META-INF/plugin.xml
This hasn't been working since 2019.2
=> Fix building searchable options in CI

unity/EditorPlugin/RiderPathLocator.cs
https://github.com/JetBrains/resharper-unity/issues/1529
=> Support toolbox custom "Tools install location", by reading .settings.json

unity/EditorPlugin/RiderPathLocator.cs
=> Support toolbox custom "Tools install location", by reading .settings.json - 2

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/UnityDebuggerOutputListener.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/UnityInstallationFinder.kt
fix https://youtrack.jetbrains.com/issue/RIDER-40881
=> Improve failed to attach message

resharper/resharper-unity/src/ProjectModel/UnitySolutionTracker.cs, rider/src/main/kotlin/com/jetbrains/rider/UnityProjectDiscoverer.kt
https://github.com/JetBrains/resharper-unity/issues/1571
=> Consider slnf be a valid solution file extension

unity/EditorPlugin.Tests/EditorPlugin.Tests.csproj, unity/EditorPlugin/EditorPlugin.5.5.0f3.csproj, unity/EditorPlugin/EditorPlugin.csproj, unity/EditorPlugin/EditorPluginFull.csproj, unity/EditorPlugin/EditorPluginNet46.csproj, unity/EditorPlugin/EditorPluginUnity56.csproj
=> fix RD references

unity/EditorPlugin/PluginEntryPoint.cs
In case when AutoRefresh is disabled in Unity
=> Fix infinite refresh

CHANGELOG.md, resharper/resharper-unity/src/CSharp/Feature/Services/Explanatory/UnityCodeInspectionWikiDataProvider.cs, resharper/resharper-unity/src/resharper-unity.resharper.nuspec, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/PackagesRoot.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/packageManager/PackageManager.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ui/UssDisabledEditorNotification.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/UnityInstallationFinder.kt, rider/src/main/resources/META-INF/PluginCssPluginPart.xml, rider/src/main/resources/META-INF/plugin.xml
=> Net201 misc fixes

resharper/resharper-unity/src/Rider/UnityPluginInstaller.cs
together with corresponding meta files
=> Safely remove all empty folders created by older Rider version

resharper/resharper-unity/src/Rider/UnityPluginInstaller.cs, resharper/resharper-unity/src/Rider/UnityRefreshTracker.cs
https://youtrack.jetbrains.com/issue/DEXP-345283
=> Add AssertGuarded in Refresh and fix call

resharper/resharper-unity/src/Rider/UnityRefreshTracker.cs
https://github.com/JetBrains/resharper-unity/issues/1601
=> Avoid pause vfs for Unity 2018+

resharper/resharper-unity/src/UnityInstallationFinder.cs
fix https://youtrack.jetbrains.com/issue/DEXP-514198
=> fix search for Unity location in custom location of Unity Hub

resharper/resharper-unity/src/Rider/ConnectionTracker.cs, resharper/resharper-unity/src/Rider/UnityRefreshTracker.cs
=> If there is no response from Unity via protocol - change state to Disconnected

resharper/resharper-unity/src/Rider/UnityEditorProtocol.cs, unity/EditorPlugin/NonUnity/RiderProtocolController.cs
Fix problem with unresponsive backend, when Rider protocol version is higher than Unity protocol version
=> Fix problem with unresponsive backend

resharper/resharper-unity/src/Rider/CodeInsights/UnityCodeInsightFieldUsageProvider.cs, resharper/resharper-unity/src/Rider/CodeInsights/UnityInspectorCodeInsightsHighlighting.cs, resharper/resharper-unity/src/Rider/CodeInsights/UnityUsagesCodeVisionProvider.cs, resharper/resharper-unity/src/Yaml/Feature/Services/Navigation/UnityAssetOccurrence.cs, resharper/resharper-unity/src/Yaml/Feature/Services/Navigation/UnityEditorOccurencePresenter.cs, resharper/resharper-unity/src/Yaml/Feature/Services/Navigation/UnityInspectorValuesOccurrence.cs, resharper/resharper-unity/src/Yaml/Feature/Services/Navigation/UnityScriptsOccurrence.cs, resharper/resharper-unity/src/Yaml/Psi/DeferredCaches/AssetUsages/AssetUsagesElementContainer.cs, resharper/resharper-unity/src/Yaml/Psi/DeferredCaches/AssetUtils.cs, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/FormerlySerializedAsAttribute/rider/NonUnityFields.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/FormerlySerializedAsAttribute/rider/RedundantFormerlySerializedAs.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/RedundantAttributeOnTarget/rider/HideInInspector.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/Analysis/rider/RedundantSerializeFieldAttribute.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/GutterMark/rider/Test01.cs.gold
1. Show the "Serializable" code vision for all serializable fields
2. Improve presentation for find usages results (Rich text instead of string)
=> Asset integration fixes

unity/EditorPlugin/PluginSettings.cs
=> Improve detection of reference assemblies

resharper/resharper-unity/src/Settings/LangVersionProjectSettingsProvider.cs, resharper/resharper-unity/src/UnityInstallationFinder.cs
also remove backslash, fix debug-only exception on linux
=> Fix auto-detected LangVersion on Linux

CHANGELOG.md, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/packageManager/PackageManager.kt, rider/src/main/resources/META-INF/plugin.xml
Fixes [RIDER-43317](https://youtrack.jetbrains.com/issue/RIDER-43317)
=> Avoid deadlocks refreshing VFS

resharper/resharper-unity/src/Rider/ConnectionTracker.cs, resharper/resharper-unity/src/Rider/UnityRefreshTracker.cs, rider/.idea/runConfigurations/runIde__quick_mono_.xml, rider/frontend.gradle, rider/gradle.properties
fix RIDER-43222
fix RIDER-43066
=> Threading issues

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/debugger/breakpoints/ConvertToPausepointPopupActionProvider.kt
Fixes [RIDER-45368](https://youtrack.jetbrains.com/issue/RIDER-45368)
=> Hide pausepoint action on non-Unity projects

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/actions/RiderUnityLogViewAction.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/actions/UnityActions.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/UnityToolWindowFactory.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelModel.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelToolbarBuilder.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelView.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogTokenizer.kt
Not sure, if we need to:
1. Select the last item or just bring it to view.
2. Persist permachine/project that autoscroll is checked/unchecked?
=> Add autoscroll button in UnityLogView, fix RIDER-14377

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorRunConfiguration.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/UnityUtils.kt
Helps with Unity 2020.1+, which has Release by default.
=> When Rider is started by Debug run-configuration - enable debug by command line param

resharper/.idea/.idea.rider-unity/.idea/misc.xml, resharper/resharper-unity/src/CSharp/Daemon/Errors/CSharpErrors.xml
revert occasionally changed files
=> Revert occasionally changed files

resharper/resharper-unity/src/CSharp/Daemon/Errors/BurstErrors.xml, resharper/resharper-unity/src/CSharp/Daemon/Stages/BurstCodeAnalysis/Analyzers/BurstForeachStatementAnalyzer.cs, resharper/resharper-unity/src/CSharp/Daemon/Stages/BurstCodeAnalysis/Analyzers/BurstInvocationExpressionAnalyzer.cs, resharper/resharper-unity/src/CSharp/Daemon/Stages/BurstCodeAnalysis/Analyzers/BurstObjectCreationExpressionAnalyzer.cs, resharper/resharper-unity/src/CSharp/Daemon/Stages/BurstCodeAnalysis/Analyzers/BurstReferenceExpressionAnalyzer.cs, resharper/resharper-unity/src/CSharp/Daemon/Stages/BurstCodeAnalysis/Analyzers/BurstStringLiteralOwnerAnalyzer.cs, resharper/resharper-unity/src/CSharp/Daemon/Stages/BurstCodeAnalysis/Analyzers/BurstTryStatementAnalyzer.cs, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/BurstCodeAnalysis/resharper/BurstDiscardTests.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/BurstCodeAnalysis/resharper/DebugStringTests.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/BurstCodeAnalysis/resharper/DirectivesTests.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/BurstCodeAnalysis/resharper/EqualsTests.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/BurstCodeAnalysis/resharper/ExceptionsTests.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/BurstCodeAnalysis/resharper/FunctionParametersReturnTests.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/BurstCodeAnalysis/resharper/MethodInvocationTests.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/BurstCodeAnalysis/resharper/PrimitivesTests.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/BurstCodeAnalysis/resharper/ReferenceExpressionTests.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/BurstCodeAnalysis/resharper/SmartMarkingTests.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/BurstCodeAnalysis/rider/BurstDiscardTests.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/BurstCodeAnalysis/rider/DebugStringTests.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/BurstCodeAnalysis/rider/DirectivesTests.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/BurstCodeAnalysis/rider/EqualsTests.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/BurstCodeAnalysis/rider/ExceptionsTests.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/BurstCodeAnalysis/rider/FunctionParametersReturnTests.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/BurstCodeAnalysis/rider/MethodInvocationTests.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/BurstCodeAnalysis/rider/PrimitivesTests.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/BurstCodeAnalysis/rider/ReferenceExpressionTests.cs.gold, resharper/resharper-unity/test/data/CSharp/Daemon/Stages/BurstCodeAnalysis/rider/SmartMarkingTests.cs.gold
1. backticks replaced with single quotes
2. no stops at the end 
3. no compiler IDs
4. little more user-friendly wanings
5. description clarification 
6. little refactoring
=> Burst highlightings refactoring

unity/EditorPlugin/PluginEntryPoint.cs, unity/EditorPlugin/UnityEventLogSender.cs
https://youtrack.jetbrains.com/issue/RIDER-47427
=> fix RIDER-47427 Unity plugin causes error when exiting Play mode

readme.md, unity/README.md
https://github.com/JetBrains/resharper-unity/issues/214#issuecomment-657166112
=> Add uninstall information to readme

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/UnityProcessPickerDialog.kt
Fixes two issues - child worker processes would get a separator, and reloading the model in order to invalidate the cached variable row heights would collapse the expanded tree nodes, so child worker processes would "disappear" (especially tricky as there is no indication that this is a tree.
=> Fix layout issues with process picker tree

resharper/resharper-unity/src/HlslSupport/Integration/Cpp/InjectedHlslInclusionContextProvider.cs, resharper/resharper-unity/src/ShaderLab/Daemon/Stages/IdentifierHighlighterProcess.cs
1. Missed defines for surface shaders
2. Hide errors in compiled .shader files
=> Shader fixes

resharper/resharper-unity/src/Rider/UnityRefreshTracker.cs
Avoid: Infinite "Refreshing solution in UnityEditor", when there is modal dialog opened in Unity
=> avoid starting refresh, when there is no connection.RIDER-48690

resharper/resharper-unity/src/Rider/UnitTesting/UnityDebugHostProvider.cs, resharper/resharper-unity/src/Rider/UnitTesting/UnityRunHostProvider.cs, resharper/resharper-unity/src/Rider/UnitTesting/UnityTaskRunnerHostController.cs, resharper/resharper-unity/src/Rider/UnityController.cs
Fix concurrency run/debug tests
Fix compile/ Add GetUnityVersion implementation
=> Net203 fix run debug cover unity tests

resharper/resharper-unity/src/CSharp/Rider/Host/Features/RunMarkers/UnityRunMarkerAttributeIds.cs, resharper/resharper-unity/src/CSharp/Rider/Host/Features/RunMarkers/UnityRunMarkerGutterMark.cs, resharper/resharper-unity/src/CSharp/Rider/Host/Features/RunMarkers/UnityRunMarkerHighlighting.cs, resharper/resharper-unity/src/CSharp/Rider/Host/Features/RunMarkers/UnityRunMarkerProvider.cs, resharper/resharper-unity/src/CSharp/Rider/Host/Features/RunMarkers/UnityRunMarkerUtil.cs, unity/EditorPlugin/PluginEntryPoint.cs
https://youtrack.jetbrains.com/issue/RIDER-35911
=> Run Unity MenuItem from Rider

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelToolbarBuilder.kt, rider/src/main/kotlin/icons/UnityIcons.kt, rider/src/main/resources/Icons/logView/filterBeforePlay.svg, rider/src/main/resources/Icons/logView/filterBeforePlay_dark.svg, rider/src/main/resources/Icons/logView/filterBeforeRefresh.svg, rider/src/main/resources/Icons/logView/filterBeforeRefresh_dark.svg
=> icons for LogView

resharper/resharper-unity/src/Templates/File/EditorWindow.md, resharper/resharper-unity/src/Templates/File/PropertyDrawer.md, resharper/resharper-unity/src/Templates/File/ScriptableWizard.md
This closes #1856 and also improves some other editors.
=> Improved templates

resharper/resharper-unity/src/Rider/UnitTesting/RunViaUnityEditorStrategy.cs
when I explicitly select some tests from 2 different projects.
=> Fix running explicit tests

resharper/resharper-unity/src/Rider/UnitTesting/RunViaUnityEditorStrategy.cs
https://youtrack.jetbrains.com/issue/RIDER-52766
=> Add statistics for Unity unit-tests

resharper/resharper-unity/src/CSharp/Feature/Services/CodeCompletion/UnityEventFunctionBehavior.cs, resharper/resharper-unity/src/CSharp/Feature/Services/CodeCompletion/UnityEventFunctionRule.cs, resharper/resharper-unity/test/data/CSharp/CodeCompletion/Action/DoNotRenameNextDeclaration.cs, resharper/resharper-unity/test/data/CSharp/CodeCompletion/Action/DoNotRenameNextDeclaration.cs.gold, resharper/resharper-unity/test/data/CSharp/CodeCompletion/Action/RetypeNameOnExistingMethodWithDifferentArgs.cs, resharper/resharper-unity/test/data/CSharp/CodeCompletion/Action/RetypeNameOnExistingMethodWithDifferentArgs.cs.gold, resharper/resharper-unity/test/data/CSharp/CodeCompletion/Action/RetypeNameOnExistingMethodWithDifferentSignature.cs, resharper/resharper-unity/test/data/CSharp/CodeCompletion/List/RetypeNameOnExistingMethodWithDifferentSignature.cs, resharper/resharper-unity/test/data/CSharp/CodeCompletion/List/RetypeNameOnExistingMethodWithDifferentSignature.cs.gold, resharper/resharper-unity/test/data/CSharp/CodeCompletion/List/RetypeNameOnExistingMethodWithDifferentSignature2.cs, resharper/resharper-unity/test/data/CSharp/CodeCompletion/List/RetypeNameOnExistingMethodWithDifferentSignature2.cs.gold, resharper/resharper-unity/test/src/CSharp/Feature/Services/CodeCompletion/UnityEventFunctionCompletionActionTest.cs, resharper/resharper-unity/test/src/CSharp/Feature/Services/CodeCompletion/UnityEventFunctionCompletionListTest.cs
Fixing https://youtrack.jetbrains.com/issue/RIDER-52404
Also changed a bit UnityEventFunctionRule. Now if we retype method name we see only suitable suggestions.
=> Change EventFunctions completion

resharper/resharper-unity/src/CSharp/Feature/Services/ContextActions/CreateAssetMenuContextAction.cs, resharper/resharper-unity/test/data/CSharp/Intentions/ContextActions/CreateAssetMenu/Availability01.cs
=> Fixed Create Asset appearing for editor/editorwindow

resharper/resharper-unity/src/Rider/UnitTesting/RunViaUnityEditorStrategy.cs, unity/EditorPlugin/AfterUnity56/UnitTesting/TestEventsSender.cs
=> fix RIDER-54342

resharper/resharper-unity/src/CSharp/Feature/Services/LiveTemplates/Scope/UnityProjectVersionScopeProvider.cs
https://jetbrains.slack.com/archives/C53QFRZ7G/p1606750920210200
=> fix DEXP-563765

resharper/resharper-unity/src/UnityApi.cs
Fixes [DEXP-564196](https://youtrack.jetbrains.com/issue/DEXP-564196)
=> Ensure we have a context when looking up types

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/AssetsRoot.kt
https://youtrack.jetbrains.com/issue/RIDER-54876
=> Multiple assemblies with the same name causes exceptions in Unity Explorer

resharper/resharper-unity/src/Rider/UnitTesting/RunViaUnityEditorStrategy.cs
https://youtrack.jetbrains.com/issue/RIDER-54359
=> fix RIDER-54359 Refresh before tests

unity/EditorPlugin/OnOpenAssetHandler.cs, unity/EditorPlugin/PluginEntryPoint.cs
=> Start rider on mac and avoid Rider-55501

rider/src/main/kotlin/com/jetbrains/rider/internal/dump/DumpUnityExplorerAction.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/AssetsRoot.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorerNode.kt, rider/src/main/resources/META-INF/plugin.xml
=> Double-click on assembly in Unity Explorer should open it in AssemblyExplorer

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/UnityToolWindowFactory.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelModel.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelView.kt
=> Improve 'Unity Log' view performance

unity/EditorPlugin/EditorPlugin.csproj, unity/EditorPlugin/Logger/LogInitializer.cs, unity/EditorPlugin/PluginEntryPoint.cs, unity/EditorPlugin/PluginSettings.cs
https://youtrack.jetbrains.com/issue/RIDER-54352
=> Mirror EditorPlugin exceptions/errors to Unity Console

resharper/resharper-unity/src/Rider/UnitTesting/UnityRiderUnitTestCoverageAvailabilityChecker.cs
I tried and it seem to just work without any problems
=> Allow covering PlayMode Unity tests

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/DefaultRunConfigurationGenerator.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/unityExe/UnityExeDebugProfileState.kt
=> Avoid generating Debug and Play run configuration for ClassLib with Unity reference

resharper/resharper-unity/test/src/TestEnvironment.cs
logs example https://buildserver.labs.intellij.net/buildConfiguration/DotNetDiv_Wave211_Rider_Plugins_Unity_BuildPlugin/107348983?buildTab=artifacts
=> enable logging for each assembly

resharper/resharper-unity/src/Packages/PackageManager.cs
Fixes [RIDER-58636](https://youtrack.jetbrains.com/issue/RIDER-58636)
=> Fix missing packages if no packages-lock.json

resharper/resharper-unity/src/Templates/File/AssetPostprocessor.md, resharper/resharper-unity/src/Templates/File/CustomEditor.md, resharper/resharper-unity/src/Templates/File/EditModeTest.md, resharper/resharper-unity/src/Templates/File/EditorEntryPoint.md, resharper/resharper-unity/src/Templates/File/EditorWindow.md, resharper/resharper-unity/src/Templates/File/MonoBehaviour.md, resharper/resharper-unity/src/Templates/File/PlayModeTest.md, resharper/resharper-unity/src/Templates/File/PropertyDrawer.md, resharper/resharper-unity/src/Templates/File/ScriptableObject.md, resharper/resharper-unity/src/Templates/File/ScriptableWizard.md, resharper/resharper-unity/src/Templates/File/StateMachineBehaviour.md
Previously said "Unity Class", now says "Unity Script"
=> Rename file template group to "Unity Script"

resharper/resharper-unity/src/Rider/UnitTesting/RunViaUnityEditorStrategy.cs, resharper/resharper-unity/src/Rider/UnitTesting/UnitTestRunEx.cs, resharper/resharper-unity/src/Rider/UnitTesting/UnityNUnitServiceProvider.cs, resharper/resharper-unity/src/annotations/UnityEngine.TestRunner.xml
Uncomment those line after https://youtrack.jetbrains.com/issue/RSRP-483699 is done
=> Temporary fix compilation

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelModel.kt
=> RIDER-59689 unity log is not cleared

resharper/resharper-unity/src/Cg/Psi/Parsing/Chars.lex, resharper/resharper-unity/src/JsonNew/Psi/Parsing/Chars.lex, resharper/resharper-unity/src/ShaderLab/Psi/Parsing/Chars.lex, resharper/resharper-unity/src/resharper-unity.csproj, resharper/resharper-unity/src/rider-unity.csproj, resharper/resharper-yaml/src/Psi/Parsing/Chars.lex, resharper/resharper-yaml/src/resharper-yaml.csproj, resharper/resharper-yaml/src/rider-yaml.csproj
based on https://jetbrains.slack.com/archives/GBGJW78SZ/p1616597534013800
=> lex fix compile

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/asmdef/AsmDefFileType.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/UnityDebuggerOutputListener.kt
https://youtrack.jetbrains.com/issue/DEXP-586697
=> fix DEXP-586697

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorRunConfiguration.kt
Only show "Unable to automatically discover correct Unity Editor to debug" for debug. Avoid showing it for Profile.
=> Minor issue with attempt to Profile from UnityClassLib

resharper/resharper-unity/src/CSharp/Feature/Services/Navigation/GoToUnityUsages/GoToUnityUsagesProvider.cs, unity/EditorPlugin/AfterUnity56/Navigation/Initialization.cs, unity/EditorPlugin/AfterUnity56/Navigation/ShowUtil.cs
see https://github.com/JetBrains/resharper-unity/pull/2124#issuecomment-890868130
Planned for backport to 212.
=> Show in unity fix for `package@version` in path

CHANGELOG.md, resharper/resharper-unity/src/Packages/PackageManager.cs
Fixes [RIDER-65196](https://youtrack.jetbrains.com/issue/RIDER-65196), fixes #2122
=> Resolve built in packages against local package cache

unity/EditorPlugin/AfterUnity56/UnitTesting/ClientControllerWrapper.cs, unity/EditorPlugin/AfterUnity56/UnitTesting/UnityEditorTestLauncher.cs
Unit tests code coverage is broken in Rider
=> Fix RIDER-68334

resharper/resharper-unity/src/Rider/UnityInstallationSynchronizer.cs, resharper/resharper-unity/src/UnityVersion.cs
https://youtrack.jetbrains.com/issue/RIDER-64599
=> Move heavy task out of the main thread

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/MetaTracker.kt
fixes potential problem discussed in the https://github.com/JetBrains/resharper-unity/pull/2205 review
=> Fix potential problem with meta tracker

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/UnityFeedbackDescriptionProvider.kt
Help->Report a Bug features something like:
Unity: 2020.3.14f1, JetBrains Rider package: 3.0.8
=> add info about Rider package to Help->Report a Bug info

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ProjectExtensions.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ProtocolInstanceWatcher.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/UnityProjectDiscoverer.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/actions/ShowFileInUnityAction.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/MetaTracker.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/uxml/codeInsight/schema/UxmlSchemaProvider.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorRunConfiguration.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorViewModel.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelEventList.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/EditorInstanceJson.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/UnityUtils.kt, rider/src/test/kotlin/base/integrationTests/ScriptingAPI.Unity.kt, rider/src/test/kotlin/integrationTests/ConnectionTest.kt, rider/src/test/kotlin/unityExplorer/UnityProjectModelViewExtensionsTest.kt
fix DEXP-628925
maybe fix https://youtrack.jetbrains.com/issue/DEXP-609027
=> refactor projectDir usages 

resharper/resharper-unity/src/Rider/UnitTesting/UnityRiderUnitTestCoverageAvailabilityChecker.cs
https://jetbrains.slack.com/archives/C53QFRZ7G/p1638181787092400
=> fix RIDER-71376, RIDER-71377, RIDER-71375

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/UnityUtils.kt
https://youtrack.jetbrains.com/issue/RIDER-62209
=> Net213 fix debug project with spaces

unity/EditorPlugin/AfterUnity56/Navigation/Window/FindUsagesWindow.cs
see https://youtrack.jetbrains.com/issue/RIDER-71754
=> Net221 expand usages window

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/DefaultRunConfigurationGenerator.kt, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/UnityUtils.kt
fix https://youtrack.jetbrains.com/issue/RIDER-70675
=> Generate run configuration for batchmode tests

resharper/resharper-unity/src/Unity/Core/Application/UI/Help/ShowUnityHelp.cs
relates to https://github.com/JetBrains/resharper-unity/issues/306
=> fix for possible location of local unity documentation

rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ProtocolInstanceWatcher.kt
RIDER-73901 Unity gets disconnected after pressing "Refresh Unity Assets" button
=> fix RIDER-73901

rider/src/main/resources/META-INF/plugin.xml
=> add controller;anim extensions as UnityYamlFileType

resharper/resharper-unity/src/Unity/UnityEditorIntegration/Packages/PackageManager.cs, rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/notifications/OpenUnityProjectAsFolderNotification.kt
=> fix showing notification for the case when folder is opened instead o sln
